In [2]:
import math
import numpy as np
import sympy
import time 

In [3]:
def calc_time(start, end):
    seconds = end - start
    mins = seconds / 60
    print('Time in seconds: ', str(seconds), ', Time in minutes: ', str(mins))
    return seconds, mins

In [4]:
# Final optimized version 
def get_primes_less_thanB(bound):                      # eratosthenes way
    check_until = int(bound**0.5)
    unmarked = np.array([x for x in range(2, bound)])
    q = 2
    i = 0
    while True:
        u = unmarked[i]
        if u> check_until:               # only check numbers up to sqrt(bound)
            break
        u_idx = np.where(unmarked == u)[0][0]
        max_idx = bound//u
        listof_multiples = [u*i for i in range(q, max_idx+1)]
        u_multiples = np.array(listof_multiples)
        unmarked = np.setdiff1d(unmarked, u_multiples)   # numpy set diff without changing order of elements in list
        q = u
        i +=1
    print("Number of elements less than bound = ", bound, " is: ", len(unmarked))
    return (unmarked)

In [5]:
# Correct optimized version
def check_Bsmooth(primes, num):
    powers_of_primes= []
    num_remaining= num                         
    for prime in primes: 
        i = 0                                   # i = power of prime
        if (num_remaining%prime == 0):
            while (num_remaining%prime ==0):   #keep dividing for each power of the prime
                quotient = num_remaining/prime
                num_remaining = quotient
                i +=1
        powers_of_primes.append(i)
        if num_remaining == 1:     
            diff = len(primes)-len(powers_of_primes)
            if diff>0:
                zeros = [0 for k in range(diff)]
                return powers_of_primes + zeros
            return powers_of_primes
    #print("Number is not B smooth")
    return []

#### Start Choosing parameters for testing: bound, n, etc;

In [6]:
def a_congruent_b(a, b, n):
    if a==(b%n):
        return True
    return False

In [7]:
def generate_BSsquares(primes, n, multiple):     # nothing here has numpy structure
    exponents_list = []
    xsquares = []           # the x
    residues = []           # the y
    iters = 0
    while(True):
        if iters>100000000:
            break
        xsquare = (int(math.sqrt(n*multiple)) +1)**2
        # Add other fancy ways of finding candidates for xsquare
        residue = xsquare%n
        exp_vec = check_Bsmooth(primes, residue)
        if exp_vec != []:
            residues.append(residue)   # x^2
            xsquares.append(xsquare)
            exponents_list.append(exp_vec)
            print("Found B-smooth square! with exponents: ", exp_vec, " and quadratic residue: ", residue)
        if len(residues) > len(primes):
            print("Breaking, len of residues: ", len(residues), " len of primes: ", len(primes))
            break
        iters += 1
        multiple += 1
    return [exponents_list, residues, iters, xsquares]

#### Test 1: a simple test on a small prime! 

In [8]:
# A first simulation
bound = 100
primes = np.array(get_primes_less_thanB(bound))

Number of elements less than bound =  100  is:  25


In [9]:
# Sample test of the function above
n = 95775679
#A_const = (math.sqrt(2)-1)*math.sqrt(n)-1      
multiple = 1
start = time.time()

results = generate_BSsquares(primes, n, multiple)

end = time.time()
calc_time(start, end)
print("iterations, ", results[2])
print("B smooth numbers found: ", results[1], "\ntotal: ", len(results[1]))

Found B-smooth square! with exponents:  [1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  and quadratic residue:  9690
Found B-smooth square! with exponents:  [3, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  and quadratic residue:  38760
Found B-smooth square! with exponents:  [5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  and quadratic residue:  17696
Found B-smooth square! with exponents:  [2, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]  and quadratic residue:  52380
Found B-smooth square! with exponents:  [0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]  and quadratic residue:  53845
Found B-smooth square! with exponents:  [7, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  and quadratic residue:  70784
Found B-smooth square! with exponents:  [4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]  an

##### Test 2: on larger prime - just copy paste the block from above and change n

In [88]:
n = 62615533
multiple = 1
start = time.time()

results = generate_BSsquares(primes, n, multiple)

end = time.time()
calc_time(start, end)
print("iterations, ", results[2])
print("B smooth numbers found: ", results[1], "\ntotal: ", len(results[1]))

Found B-smooth square! with exponents:  [2 2 0 0 0 0 0 0 0 0 0 0 0 0 0]  and quadratic residue:  36
Found B-smooth square! with exponents:  [4 2 0 0 0 0 0 0 0 0 0 0 0 0 0]  and quadratic residue:  144
Found B-smooth square! with exponents:  [2 4 0 0 0 0 0 0 0 0 0 0 0 0 0]  and quadratic residue:  324
Found B-smooth square! with exponents:  [6 2 0 0 0 0 0 0 0 0 0 0 0 0 0]  and quadratic residue:  576
Found B-smooth square! with exponents:  [2 2 2 0 0 0 0 0 0 0 0 0 0 0 0]  and quadratic residue:  900
Found B-smooth square! with exponents:  [4 4 0 0 0 0 0 0 0 0 0 0 0 0 0]  and quadratic residue:  1296
Found B-smooth square! with exponents:  [2 2 0 2 0 0 0 0 0 0 0 0 0 0 0]  and quadratic residue:  1764
Found B-smooth square! with exponents:  [8 2 0 0 0 0 0 0 0 0 0 0 0 0 0]  and quadratic residue:  2304
Found B-smooth square! with exponents:  [2 6 0 0 0 0 0 0 0 0 0 0 0 0 0]  and quadratic residue:  2916
Found B-smooth square! with exponents:  [4 2 2 0 0 0 0 0 0 0 0 0 0 0 0]  and quadratic r

#### # Test 3: on even larger prime - again copy paste the block from above and change n
#### Trials 1, 2: oops, did not work? - Changed break point to be 100 fold more than for the other 2
##### Result: Not bad!

In [93]:
n = 169214564391    # 12 digits :))
multiple = 2
start = time.time()

results = generate_BSsquares(primes, n, multiple)

end = time.time()
calc_time(start, end)
print("iterations, ", results[2])
print("B smooth numbers found: ", results[1], "\ntotal: ", len(results[1]))

Found B-smooth square! with exponents:  [0 2 0 2 0 0 0 0 0 1 1 0 2 1 0]  and quadratic residue:  28657245897
Found B-smooth square! with exponents:  [2 2 0 2 0 0 0 0 0 1 1 0 2 1 0]  and quadratic residue:  114628983588
Found B-smooth square! with exponents:  [0 2 3 0 0 1 0 3 0 0 0 0 1 0 0]  and quadratic residue:  4112827875
Found B-smooth square! with exponents:  [6 6 0 0 0 1 0 0 0 1 0 0 1 0 1]  and quadratic residue:  33894604224
Found B-smooth square! with exponents:  [2 2 3 0 0 1 0 3 0 0 0 0 1 0 0]  and quadratic residue:  16451311500
Found B-smooth square! with exponents:  [3 5 0 2 0 0 1 0 0 0 0 0 1 2 0]  and quadratic residue:  122761455768
Found B-smooth square! with exponents:  [0 2 0 1 0 2 1 2 0 1 0 0 0 1 0]  and quadratic residue:  81479776833
Found B-smooth square! with exponents:  [0 4 3 0 0 1 0 3 0 0 0 0 1 0 0]  and quadratic residue:  37015450875
Found B-smooth square! with exponents:  [8 6 0 0 0 1 0 0 0 1 0 0 1 0 1]  and quadratic residue:  135578416896
Found B-smooth sq

In [105]:
n = 10710336959293   # 13 digits :))
multiple = 2
start = time.time()

results = generate_BSsquares(primes, n, multiple)

end = time.time()
calc_time(start, end)
print("iterations, ", results[2])
print("B smooth numbers found: ", results[1], "\ntotal: ", len(results[1]))


Found B-smooth square! with exponents:  [0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 2 1 0 0 0 0 0 0 0 0 1 0]  and quadratic residue:  3681958220435
Found B-smooth square! with exponents:  [4 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 2 0 0 1 0 0 0 0 0 0 0 0 1]  and quadratic residue:  2008158865296
Found B-smooth square! with exponents:  [6 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 2 0 0 1 0 0 0 0 0 0 0 0 1]  and quadratic residue:  8032635461184
Found B-smooth square! with exponents:  [1 1 2 0 1 0 0 1 0 0 0 0 0 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]  and quadratic residue:  139958595150
Found B-smooth square! with exponents:  [0 1 3 0 0 1 1 0 0 0 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]  and quadratic residue:  11186218875
Found B-smooth square! with exponents:  [3 1 2 0 1 0 0 1 0 0 0 0 0 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]  and quadratic residue:  559834380600
Found B-smooth square! with exponents:  [0 1 1 3 0 2 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]  and quadratic residue:  2419012471785
Found B-smooth sq

#### Try for 16 digits, professor's number!

In [65]:
# Try a bigger bound - does it help runtime?
bound = 250
primes = np.array(get_primes_less_thanB(bound))

Number of elements less than bound =  250  is:  53


In [1]:
# n = 6817540046645387   # 16 digits
# multiple = 3
# start = time.time()

# results = generate_BSsquares(primes, n, multiple)

# end = time.time()
# calc_time(start, end)
# print("iterations, ", results[2])
# print("B smooth numbers found: ", results[1], "\ntotal: ", len(results[1]))

In [14]:
# Run this cell only when you do keyboard interrupt (after getting frustrated about it not ending)
# end = time.time()
# calc_time(start, end)
# print("iterations, ", results[2])
# print("B smooth numbers found: ", results[1], "\ntotal: ", len(results[1]))

## Can run on 'results, n' produced from last run cell 

In [10]:
def drop_zero_rows(A): 
    return A[~np.all(A == 0, axis=1)]

In [11]:
from sympy import *          # Start using np arrays

A = np.array(results[0])      # results = [exponents_list, residues, iters, xsquares]
store_pows = A.copy()
A = (np.transpose(A))%2
print(A)

[[1 1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0]
 [1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 1 1 0 0]
 [1 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1]
 [1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 

In [12]:
col_num = len(A[0])
row_num = len(A)
print("Old num rows and num columns: ", row_num, col_num)
L = Matrix(A)

L = np.array(L.rref()[0])      # reduced row echelon form
L2  = drop_zero_rows(L)        # get rid of primes we don't have to worry about in general
L2 = L2 %2

print("Reduced row echelon form AND mod 2 is: ")
print(L2)

print("New num rows, num columns: ", len(L2), len(L2[0]))

Old num rows and num columns:  25 26
Reduced row echelon form AND mod 2 is: 
[[1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0

In [31]:
## Choose free variables:
def getA_solution(reduced_matrix):
    L = reduced_matrix
    col_num = len(L[0])
    row_num = len(L)
    v = np.ones(col_num, dtype = 'int')
    for i in reversed(range(row_num)):
        for j in reversed(range(col_num)):
            if L[i][j] ==1:
                #print("found row, col:", i, j, " with 1")
                if (L[i].sum()%2) !=0:              # the exponents for this prime doesn't add up to zero
                    v[j] = 0                  # can't use this equation
                    break     # no need to  check cells above, as reduced echelon form
    return(v)


In [32]:
v = getA_solution(L2)
print(v)

[1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]


In [30]:
# print(store_pows)    # equations are rows = columns in v- vector
# subset = []                 # stores only the relevant (subset of) exponent vectors 
# for i in range(len(v)):
#     if v[i] ==0:
#         continue
#     subset.append(store_pows[i])  
# print("Had initially this many equations: ", len(store_pows))
# print("Now choosing only as many equations as: ", len(subset))
#print(subset)

Had initially this many equations:  26
Now choosing only as many equations as:  6


In [43]:
def get_product_ysquared(v, results):    # results = [exponents_list, residues, iters, xsquares]
    residues = results[1]
    product_ysquare = 1       # RHS, y^2
    for i in range(len(v)):
        if v[i] ==0:
            continue
        product_ysquare = product_ysquare * residues[i]
        product_ysquare = product_ysquare%n
#     print(product_ysquare)

In [42]:
def get_product_xsquared(v, results):     # results = [exponents_list, residues, iters, xsquares]
    xsquares = results[3]
    product_xsquare = 1       # RHS, y^2
    for i in range(len(v)):
        if v[i] ==0:
            continue
        product_xsquare = product_xsquare * xsquares[i]
        product_xsquare = product_xsquare%n
#     print(product_xsquare)

In [51]:
product_xsquare = get_product_xsquared(results)     # results[2] = xsquares (candidates that worked)
product_ysquare = get_product_ysquared(results)   # results[1] = residues

## Didn't finish the run with n = 95775679, so don't run below. GTG somewhere

In [38]:
# def get_product_modN(np_1Darray, n):
#     pythlist = np_1Darray.tolist()
#     product = 1
#     for i in range(len(pythlist)):
#         product *= pythlist[i]
#         product = product%n
#     return product

In [41]:
# nparr = np.array([2, 3, 5, 7])
# print(get_pythlist_product(nparr))

In [53]:
print("final x square: ", product_xsquare, " final y square: ", product_ysquare)

final x square:  535855603600296  final y square:  4233396074491038


In [54]:
x = product
y = final_y_square

In [55]:
k = math.gcd(x -int(y), n)
print(k)
print (int(n/k)) 

1
6817540046645387


### END HERE