In [6]:
def choose_B():
    return 20

In [7]:
def get_primes_less_thanB(bound):                      # eratosthenes way
    start = 2
    unmarked = set([x for x in range(bound)])
    unmarked.remove(0)
    unmarked.remove(1)
    
    repeat_list = []
    q = 2
    for u in unmarked:           # this is still heavily inefficient, since unmarked has all numbers up to bound, so it--
                                # --checks numbers that are non-prime, as well!
        if u> int(bound**0.5):      # only check numbers up to sqrt(bound)
            break
        while u*q<= bound:
            repeat_list.append(u*q)
            unmarked = unmarked - set(repeat_list)
            q+=1
        q = 2
    return (list(unmarked))

In [8]:
def check_Bsmooth(num, bound):
    primes_less_thanB = get_primes_less_thanB(bound)
    powers_of_primes= []
    num_remaining= num                          # keep dividing by primes in B smooth primes, until == 1
    for prime in primes_less_thanB:
        i = 0                                   # i = power of prime
        if (num_remaining%prime == 0):
            # print(prime)
            while (num_remaining%prime ==0):   #keep dividing for each power of the prime
                quotient = num_remaining/prime
                num_remaining = quotient
                i +=1
        # print(i)
        powers_of_primes.append(i)
    if num_remaining == 1:
        print("Number is B smooth, using primes:", primes_less_thanB, "with corresponding powers:", powers_of_primes)
        return powers_of_primes
    print("Number is not B smooth")
    return []

In [9]:
bound = choose_B()
n = 63787
num1 =  (439**2)%n
num2 = (444**2)%n
num3 = (445**2)%n
num4 = (447**2)%n
num5 = (449**2)%n

result1 = check_Bsmooth(num1, bound)
result2 = check_Bsmooth(num2, bound)
result3 = check_Bsmooth(num3, bound)
result4 = check_Bsmooth(num4, bound)
result5 = check_Bsmooth(num5, bound)

results = [result1, result2, result3, result4, result5]

Number is B smooth, using primes: [2, 3, 5, 7, 11, 13, 17, 19] with corresponding powers: [4, 0, 1, 0, 0, 0, 1, 0]
Number is B smooth, using primes: [2, 3, 5, 7, 11, 13, 17, 19] with corresponding powers: [0, 1, 2, 1, 1, 0, 0, 0]
Number is B smooth, using primes: [2, 3, 5, 7, 11, 13, 17, 19] with corresponding powers: [3, 0, 0, 2, 0, 0, 1, 0]
Number is B smooth, using primes: [2, 3, 5, 7, 11, 13, 17, 19] with corresponding powers: [8, 1, 0, 0, 1, 0, 0, 0]
Number is B smooth, using primes: [2, 3, 5, 7, 11, 13, 17, 19] with corresponding powers: [11, 0, 1, 0, 0, 0, 0, 0]


In [10]:
import numpy as np
import numpy.linalg

matrix = []
for result in results:
    if result != "[]":
        matrix.append(result)
np_array = np.array(matrix)
print(np_array)

[[ 4  0  1  0  0  0  1  0]
 [ 0  1  2  1  1  0  0  0]
 [ 3  0  0  2  0  0  1  0]
 [ 8  1  0  0  1  0  0  0]
 [11  0  1  0  0  0  0  0]]


In [11]:
np_array_mod2 = (np_array%2)

In [12]:
print(np_array_mod2)

[[0 0 1 0 0 0 1 0]
 [0 1 0 1 1 0 0 0]
 [1 0 0 0 0 0 1 0]
 [0 1 0 0 1 0 0 0]
 [1 0 1 0 0 0 0 0]]


In [15]:
matA = np_array_mod2
zeros = np.array([[0 for i in range(len(matA))]]) # all zeroes is what we want
# np.linalg.lstsq(matA, matB)

In [60]:
def upp_triangular(num_rows, num_cols, aug_matA):
    A = aug_matA
    n = num_rows
    m = num_cols
    for i in range(m): # for each column
        if i>=n:
            break
        print("row num: ", i)
        print("current matrix ", A)
        A = A%2
        print("A mod 2: ", A)
        maxi = i
        for k in range(i, n): # find the row at i or below where entry is 1
            if A[k][i] ==1:
                maxi = k
                break
        print("finished looping through rows")
        if A[maxi][i] != 1:  # whole loop was executed without finding a '1'- entry in any row
            print("No column entry has a 1")
            continue
    #         print("Getting rid of the entire column i of zeros", str(i), "...")
    #         for j in range(n):
    #             A[j].pop(i)

        else: # some row = maxi row has a 1 entry
            print("found a row with a 1 entry = ", maxi)
            if maxi != i:# need swap rows
                print ("Swapping rows for row = ", i, "and maxi = ", maxi)
                print("A[i] before swap: ", A[i])
                print("A[maxi] before swap: ", A[maxi])
                currenti = A[i].copy()
                # currentmaxi = A[maxi]
                A[i] = A[maxi]
                A[maxi] = currenti
                print("A[i] after swap: ", A[i])
                print("A[maxi] after swap: ", A[maxi])
                print("matrix overall after swap: ", A)
            for j in range(i+1, n):    # check every entry directly below A[i][i] 
                belowi = A[j][i]
                print("belowi: ", belowi)
                if belowi !=0: # if entry is 1 for any row, nullify it
                    A[j]+= -A[i]
                    print("belowi non zero: ", belowi, "for j = ", j)
                    print("A[j] after adding row -A[i] to it", A[j])

    # should have upper triangular matrix at the end of this 
    return A

In [61]:
a = matA
b = zeros
n = len(matA)     # row number + number of unknowns
m = len(matA[0])        # column number + number of unknowns
a = np.concatenate((a, b.T), axis=1)
print(a) 

[[0 0 1 0 0 0 1 0 0]
 [0 1 0 1 1 0 0 0 0]
 [1 0 0 0 0 0 1 0 0]
 [0 1 0 0 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 0]]


In [62]:
aug_matrix = a
row_num = len(a)
col_num = len(a[0])

upp_triangular(row_num, col_num,  aug_matrix)
# [[1 0 0 0 0 0 1 0 0]
#  [0 1 0 1 1 0 0 0 0]
#  [0 0 1 0 0 0 1 0 0]
#  [0 1 0 0 1 0 0 0 0]
#  [1 0 1 0 0 0 0 0 0]]

row num:  0
current matrix  [[0 0 1 0 0 0 1 0 0]
 [0 1 0 1 1 0 0 0 0]
 [1 0 0 0 0 0 1 0 0]
 [0 1 0 0 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 0]]
A mod 2:  [[0 0 1 0 0 0 1 0 0]
 [0 1 0 1 1 0 0 0 0]
 [1 0 0 0 0 0 1 0 0]
 [0 1 0 0 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 0]]
finished looping through rows
found a row with a 1 entry =  2
Swapping rows for row =  0 and maxi =  2
A[i] before swap:  [0 0 1 0 0 0 1 0 0]
A[maxi] before swap:  [1 0 0 0 0 0 1 0 0]
A[i] after swap:  [1 0 0 0 0 0 1 0 0]
A[maxi] after swap:  [0 0 1 0 0 0 1 0 0]
matrix overall after swap:  [[1 0 0 0 0 0 1 0 0]
 [0 1 0 1 1 0 0 0 0]
 [0 0 1 0 0 0 1 0 0]
 [0 1 0 0 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 0]]
belowi:  0
belowi:  0
belowi:  0
belowi:  1
belowi non zero:  1 for j =  4
A[j] after adding row -A[i] to it [ 0  0  1  0  0  0 -1  0  0]
row num:  1
current matrix  [[ 1  0  0  0  0  0  1  0  0]
 [ 0  1  0  1  1  0  0  0  0]
 [ 0  0  1  0  0  0  1  0  0]
 [ 0  1  0  0  1  0  0  0  0]
 [ 0  0  1  0  0  0 -1  0  0]]
A mod 2:  [[1 0 0 0 0 0 1 0 0]
 [0 1

array([[1, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [2]:
## A is n by m binary matrix
# // row and column index
## find non-zero element in column i, starting in row i:
                                 
for i := 1 to m do // for every column
  maxi := i
  for k := i to n do
    if A[k,i] = 1 then maxi := k
  end for
  if A[maxi,i] = 1 then
    swap rows i and maxi in A and b, but do not change the value of i
    Now A[i,i] will contain the old value of A[maxi,i], that is 1
    for u := i+1 to m do
      Add A[u,i] * row i to row u, do this for BOTH, matrix A and RHS vector b
      Now A[u,i] will be 0
    end for
 else
   declare error – more than one solution exist
 end if
end for
if n>m and if you can find zero row in A with nonzero RHS element, then
 declare error – no solution.
end if
// now, matrix A is in upper triangular form and solution can be found
use back substitution to find vector x

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 56)

In [14]:
# Some optimizations would be to get rid of rows such as the 8th and the 6th row which are all zeros
# Equivalent to getting rid of primes under B which don't appear in the factorization for any of the f(x)
# np.linalg.solve(matA, matB)

In [28]:
# Making numpy array of n x n+1 size and initializing 
# to zero for storing augmented matrix
# a = np.zeros((n,n+1))
a = matA
b = zeros
n = len(matA[0])     # number of unknowns
m = len(matA)
a = np.concatenate((a, b.T), axis=1)
#print(a)
# Making numpy array of n size and initializing 
# to zero for storing solution vector
x = np.zeros(n)

# Applying Gauss Elimination
for i in range(m):   # m = #columns
    if a[i][i] == 0:
        #print('Divide by zero detected!')
        continue
        
    for j in range(i+1, m):
        ratio = a[j][i]/a[i][i]
        print(ratio)
        
        for k in range(n+1):
            a[j][k] = a[j][k] - ratio * a[i][k]
print(a)

# Back Substitution -->not yet working
x[n-1] = a[n-1][n]/a[n-1][n-1]

for i in range(n-2,-1,-1):
    x[i] = a[i][n]
    
    for j in range(i+1,n):
        x[i] = x[i] - a[i][j]*x[j]
    
    x[i] = x[i]/a[i][i]

# Displaying solution
print('\nRequired solution is: ')
for i in range(n):
    print('X%d = %0.2f' %(i,x[i]), end = '\t')

[[0 0 1 0 0 0 1 0 0]
 [0 1 0 1 1 0 0 0 0]
 [1 0 0 0 0 0 1 0 0]
 [0 1 0 0 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 0]]
Divide by zero detected!
0.0
1.0
0.0
Divide by zero detected!
-0.0
Divide by zero detected!
[[ 0  0  1  0  0  0  1  0  0]
 [ 0  1  0  1  1  0  0  0  0]
 [ 1  0  0  0  0  0  1  0  0]
 [ 0  0  0 -1  0  0  0  0  0]
 [ 1  0  1  0  0  0  0  0  0]]


IndexError: index 7 is out of bounds for axis 0 with size 5

In [21]:
# Noticing the failures with linalg.solve and linalg.lstsq, I proceed to implement Guassian myself!

def Gauss_elm(matA): # only with row swaps and addition
    matB = [0 for i in range(len(matA))]
    for i in range(len(matA)):     # for each equation, check if some combination of adding other rows nullifies it
        for col in range(i, len(matA[0])): # for columns of this row not yet nullified
            if col[i] ==0:
                continue
            for k in range(len(matA)):
                if matA[k][]
            
    

SyntaxError: invalid syntax (<ipython-input-21-86b886617551>, line 10)