I got quite frustrated about the Gaussian elimination. I don't understand what others were exactly doing,
 but solving Ax=0 when rank(A) is smaller than #rows in matrix A seems to be almost always solved by the 
 method of 'inspection', in the resources I found online.
 Hence, I decided to assume we will generate a square matrix for now

In [43]:
import numpy as np
import time

In [ ]:
import math
def gcd(a, b):
    if (a==0 or b==0):
        return 0
    r = b%a
    if r==0:
        return b//a
    if r==1:
        return 1
    return gcd(b, r)

In [ ]:
print("gcd of 7 and 14 is: ", str(gcd(7, 14)))
print("gcd of 57 and 768 is: ", str(gcd(57, 768)))

In [11]:
def calc_time(start, end):
    seconds = end - start
    mins = seconds / 60
    print('Time:', str(seconds), '    ', str(mins))
    # return seconds, mins

In [54]:
# got rid of the inefficiency of last time

def get_primes_less_thanB(bound):                      # eratosthenes way
    check_until = int(bound**0.5)
    unmarked = np.array([x for x in range(2, bound)])
#     unmarked = [x for x in range(2, bound+1)]
    q = 2
    i = 0
    while True:
        u = unmarked[i]
#         if i%5 ==0:
#             print("In this iteration, u = ", u)
        #print("current unmarked elements", unmarked)
        if u> check_until:               # only check numbers up to sqrt(bound)
            break
        u_idx = np.where(unmarked == u)[0][0]
        #print("u index ", u_idx)
        max_idx = bound//u
        #print("max index of u: ", max_idx)
        listm = [u*i for i in range(q, max_idx+1)]
        #print(listm)
        u_multiples = np.array(listm)
        unmarked = np.setdiff1d(unmarked, u_multiples)
#         while u*q<= bound:
#             if u*q in unmarked:
#                 unmarked.remove(u*q)
#             q+=1
        q = u
        i +=1
#         print("Elements still unmarked: ", unmarked)
    # print("final unmarked elements (for eye balling!): ", unmarked)
    print("number of elements less than bound = ", bound, " is: ", len(unmarked))
    return (list(unmarked))

In [55]:
start = time.time()
bound = 100000
x = get_primes_less_thanB(bound)
end = time.time()
calc_time(start, end)

In this iteration, u =  2
In this iteration, u =  13
In this iteration, u =  31
In this iteration, u =  53
In this iteration, u =  73
In this iteration, u =  101
In this iteration, u =  127
In this iteration, u =  151
In this iteration, u =  179
In this iteration, u =  199
In this iteration, u =  233
In this iteration, u =  263
In this iteration, u =  283
In this iteration, u =  317
number of elements less than bound =  100000  is:  9592
Time: 0.16432452201843262      0.0027387420336405436


In [45]:
start = time.time()
bound = 10000
x = get_primes_less_thanB(bound)
end = time.time()
calc_time(start, end)

final unmarked elements (for eye balling!):  [   2    3    5 ... 9949 9967 9973]
number of elements less than bound is:  1229
Time: 0.021973609924316406      0.0003662268320719401


In [ ]:
############
##########
#######
####
##
#

In [26]:
start = time.time()
bound = 10000
x = get_primes_less_thanB(bound)
end = time.time()
calc_time(start, end)

final unmarked elements (for eye balling!):  [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997, 1009, 1013, 1019, 1021, 1031, 1033, 1039, 1049, 1051, 1061, 1063, 1069, 1087, 1091, 1093, 1097, 1103, 1109, 1117, 1123, 1129, 1151, 1153, 1163,

In [27]:
# Fixed the bug!!
print(len(x))

1229


In [11]:
def check_Bsmooth(num, bound):
    primes_less_thanB = get_primes_less_thanB(bound)
    powers_of_primes= []
    num_remaining= num                          # keep dividing by primes in B smooth primes, until == 1
    for prime in primes_less_thanB:
        i = 0                                   # i = power of prime
        if (num_remaining%prime == 0):
            while (num_remaining%prime ==0):   #keep dividing for each power of the prime
                quotient = num_remaining/prime
                num_remaining = quotient
                i +=1
        powers_of_primes.append(i)
    if num_remaining == 1:
        print("Number is B smooth, using primes:", primes_less_thanB, "with corresponding powers:", powers_of_primes)
        return powers_of_primes
    print("Number is not B smooth")
    return []

In [12]:
# Some tests
bound = 20
n = 63787
num1 =  (439**2)%n
num2 = (444**2)%n
num3 = (445**2)%n
num4 = (447**2)%n
num5 = (449**2)%n

result1 = check_Bsmooth(num1, bound)
result2 = check_Bsmooth(num2, bound)
result3 = check_Bsmooth(num3, bound)
result4 = check_Bsmooth(num4, bound)
result5 = check_Bsmooth(num5, bound)

results = [result1, result2, result3, result4, result5]


Number is B smooth, using primes: [2, 3, 5, 7, 11, 13, 17, 19] with corresponding powers: [4, 0, 1, 0, 0, 0, 1, 0]
Number is B smooth, using primes: [2, 3, 5, 7, 11, 13, 17, 19] with corresponding powers: [0, 1, 2, 1, 1, 0, 0, 0]
Number is B smooth, using primes: [2, 3, 5, 7, 11, 13, 17, 19] with corresponding powers: [3, 0, 0, 2, 0, 0, 1, 0]
Number is B smooth, using primes: [2, 3, 5, 7, 11, 13, 17, 19] with corresponding powers: [8, 1, 0, 0, 1, 0, 0, 0]
Number is B smooth, using primes: [2, 3, 5, 7, 11, 13, 17, 19] with corresponding powers: [11, 0, 1, 0, 0, 0, 0, 0]


In [ ]:
# If we wanna save the result in a stupid way; 
# was going to try geopandas (gpd) "to_file" method, but my BASE environment is not downloading geopandas!
# (need to try in the custom environment; that already has gpd library installed)
with open ("./Data/example1.txt", "w") as filehandle:
    for row in results:
        for col in row:
            filehandle.write(str(col))
        filehandle.write("\n")


In [21]:
# Using numpy
import numpy as np
# import geopandas as gpd

matrix = []
for result in results:
    if result != "[]":
        matrix.append(result)
np_array = np.array(matrix)
# print(np_array)


In [22]:
import numpy.linalg
a = (np_array%2)
n = len(a)            # row number + number of equations we have
m = len(a[0])        # column number + number of primes (in factor base)

b =  np.array([[0 for i in range(n)]])     # all zeros
# r = np.array([[i] for i in range(n)])
a = np.concatenate((a, b.T), axis=1)
# a = np.concatenate((a, r.T), axis=1)
print(a)

[[0 0 1 0 0 0 1 0 0]
 [0 1 0 1 1 0 0 0 0]
 [1 0 0 0 0 0 1 0 0]
 [0 1 0 0 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 0]]


In [23]:
# Ignore for now; was trying to create a different kind of augmented matrix

# rules = [[i] for i in range(10)]
# print(rules)

In [24]:
def zero_row(A):
    bool_rows = ~A.any(axis=1)
    return bool_rows.any(axis=0)

In [ ]:
zero_row_idx(A):
    return np.where(~A.any(axis=1))[0][0]     # return first instance of zero entry

In [25]:
def upp_triangular(num_rows, num_cols, aug_matA):
    A = aug_matA
    n = num_rows
    m = num_cols
    row_adds = []
    swaps = []
    for i in range(m):            # column
        if i>=n:    
            break
        print("row num: ", i)
        A = A%2
        print("current matrix ", A)
        maxi = i
        for k in range(i, n):                 # first row at i or below where entry is 1 - pivot for that column
            if A[k][i] ==1:
                maxi = k
                break
        print("finished looping through rows")
        if A[maxi][i] != 1:                    # no '1'- entry in any row for this column
            print("No pivots in this column")
            continue
        else:                                 # some row = maxi row has a 1 entry
            print("found a row with a 1 entry, which is: row ", maxi)
            if maxi != i:            # need to swap rows
                print ("Swapping rows for row = ", i, "and maxi = ", maxi)
                currenti = A[i].copy()
                A[i] = A[maxi]
                A[maxi] = currenti
                print("matrix overall after swap: ", A)
                swaps.append((i,maxi))
            for j in range(i+1, n):          # check every entry directly below pivot/A[i][i] 
                belowi = A[j][i]
                print("belowi: ", belowi)
                if belowi !=0:              # if entry is 1 for any row
                    A[j]+= A[i]             # nullify it 
                    row_adds.append((i,j))
                    print("belowi non zero: ", belowi, "for row = ", j)
                    print("A[j] after adding row A[i] to it", A[j])
    # should have upper triangular matrix at the end of this 
    if zero_row(A):
        zero_idx = zero_row_idx(A)
        return (swaps, row_adds, zero_idx)
    return []
    


In [26]:
aug_matrix = a
row_num = len(a)
col_num = len(a[0])

result = upp_triangular(row_num, col_num,  aug_matrix)

row num:  0
current matrix  [[0 0 1 0 0 0 1 0 0]
 [0 1 0 1 1 0 0 0 0]
 [1 0 0 0 0 0 1 0 0]
 [0 1 0 0 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 0]]
finished looping through rows
found a row with a 1 entry, which is: row  2
Swapping rows for row =  0 and maxi =  2
matrix overall after swap:  [[1 0 0 0 0 0 1 0 0]
 [0 1 0 1 1 0 0 0 0]
 [0 0 1 0 0 0 1 0 0]
 [0 1 0 0 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 0]]
belowi:  0
belowi:  0
belowi:  0
belowi:  1
belowi non zero:  1 for row =  4
A[j] after adding row A[i] to it [2 0 1 0 0 0 1 0 0]
row num:  1
current matrix  [[1 0 0 0 0 0 1 0 0]
 [0 1 0 1 1 0 0 0 0]
 [0 0 1 0 0 0 1 0 0]
 [0 1 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 1 0 0]]
finished looping through rows
found a row with a 1 entry, which is: row  1
belowi:  0
belowi:  1
belowi non zero:  1 for row =  3
A[j] after adding row A[i] to it [0 2 0 1 2 0 0 0 0]
belowi:  0
row num:  2
current matrix  [[1 0 0 0 0 0 1 0 0]
 [0 1 0 1 1 0 0 0 0]
 [0 0 1 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0]]
finished looping through

([(0, 2)], [(0, 4), (1, 3), (2, 4)])

In [ ]:
swaps = results[0]
row_adds = results[1]
zero_row_idx = results[2]
for item in swaps:
    first = item[0]
    second = item[1]
    if (first == zero_row_idx) or (second == zero_row_idx):
        for row_add in row_adds:
            rowi = row_add[0]
            rowj = row_add[1]
            if (rowi == zero_row_idx) or (rowj == zero_row_idx):
                
        
    

In [38]:
a = np.array([[0, 1, 0],[1, 0, 1],[0, 0, 0],[1, 1, 0],[0, 0, 0]])
np.where(~a.any(axis=1))[0][0]


2

In [ ]:
original = a
z = results[2]
for row in result[0:z, :]:
    prime_left = primes * row      # element wise; only non-free prime remains
    any1s = row.any(axis=0)
    if len(any1s)==0:     # this equation will not have any odd primes
        continue
    elif len(any1s)==1:
        

In [ ]:
# some set of combinations led to our current zero row: how exactly was this zero row found?
notfree = []
for row in result:
    if row.any(axis=0):
        indices = np.where(a.any(axis=0))[0]
        notfree.append(indices)
for 