### This can be the final functionized version, where running the tests is easy - just change 'n' and 'bound'
### It is fast at sieving, but is not factoring properly - can you take a look at anything that looks off? 
#### Need to only check after B smooth numbers have already been generated

In [1]:
import math
import numpy as np
import sympy
import time 

In [2]:
def calc_time(start, end):
    seconds = end - start
    mins = seconds / 60
    print('Time in seconds: ', str(seconds), ', Time in minutes: ', str(mins))
    return seconds, mins

In [3]:
# Final optimized version 
def get_primes_less_thanB(bound):                      # eratosthenes way
    check_until = int(bound**0.5)
    unmarked = np.array([x for x in range(2, bound)])
    q = 2
    i = 0
    while True:
        u = unmarked[i]
        if u> check_until:               # only check numbers up to sqrt(bound)
            break
        u_idx = np.where(unmarked == u)[0][0]
        max_idx = bound//u
        listof_multiples = [u*i for i in range(q, max_idx+1)]
        u_multiples = np.array(listof_multiples)
        unmarked = np.setdiff1d(unmarked, u_multiples)   # numpy set diff without changing order of elements in list
        q = u
        i +=1
    print("Number of elements less than bound = ", bound, " is: ", len(unmarked))
    return (unmarked)

In [4]:
# Correct optimized version
def check_Bsmooth(primes, num):
    powers_of_primes= []
    num_remaining= num                         
    for prime in primes: 
        i = 0                                   # i = power of prime
        if (num_remaining%prime == 0):
            while (num_remaining%prime ==0):   #keep dividing for each power of the prime
                quotient = num_remaining/prime
                num_remaining = quotient
                i +=1
        powers_of_primes.append(i)
        if num_remaining == 1:     
            diff = len(primes)-len(powers_of_primes)
            if diff>0:
                zeros = [0 for k in range(diff)]
                return powers_of_primes + zeros
            return powers_of_primes
    #print("Number is not B smooth")
    return []

In [5]:
# Correct optimized version
def check_Bsmooth(primes, num):
    powers_of_primes= []
    num_remaining= num                         
    for prime in primes: 
        i = 0                                   # i = power of prime
        if (num_remaining%prime == 0):
            while (num_remaining%prime ==0):   #keep dividing for each power of the prime
                quotient = num_remaining/prime
                num_remaining = quotient
                i +=1
        powers_of_primes.append(i)
        if num_remaining == 1:     
            diff = len(primes)-len(powers_of_primes)
            if diff>0:
                zeros = [0 for k in range(diff)]
                return powers_of_primes + zeros
            return powers_of_primes
    #print("Number is not B smooth")
    return []

In [6]:
def a_congruent_b(a, b, n):
    if a==(b%n):
        return True
    return False

In [11]:
def generate_BSsquares(primes, n, multiple):     # nothing here has numpy structure
    exponents_list = []
    xsquares = []           # the x
    residues = []           # the y
    iters = 0
    while(True):
        if iters>100000000:
            break
        xsquare = (int(math.sqrt(n*multiple)) +1)**2
        # Add other fancy ways of finding candidates for xsquare
        residue = xsquare%n
        exp_vec = check_Bsmooth(primes, residue)
        if exp_vec != []:
            residues.append(residue)   # x^2
            xsquares.append(xsquare)
            exponents_list.append(exp_vec)
            print("Found B-smooth square! with exponents: ", exp_vec, " and quadratic residue: ", residue)
        if len(residues) > len(primes):
            print("Breaking, len of residues: ", len(residues), " len of primes: ", len(primes))
            break
        multiple += 1
        iters += 1
    return [exponents_list, residues, iters, xsquares]

#### Choose the bound value

In [12]:
bound = 100
primes = np.array(get_primes_less_thanB(bound))

Number of elements less than bound =  100  is:  25


#### Test: Choose an N of your liking (8-15 digits)

In [13]:
# A test on a small prime!
#n = 10710336959293
n = 95775679     
multiple = 4
start = time.time()

results = generate_BSsquares(primes, n, multiple)

end = time.time()
calc_time(start, end)
print("iterations, ", results[2])
print("B smooth numbers found: ", results[1], "\ntotal: ", len(results[1]))

Found B-smooth square! with exponents:  [3, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  and quadratic residue:  38760
Found B-smooth square! with exponents:  [5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  and quadratic residue:  17696
Found B-smooth square! with exponents:  [2, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]  and quadratic residue:  52380
Found B-smooth square! with exponents:  [0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]  and quadratic residue:  53845
Found B-smooth square! with exponents:  [7, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  and quadratic residue:  70784
Found B-smooth square! with exponents:  [4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]  and quadratic residue:  36208
Found B-smooth square! with exponents:  [1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]  a

### The following uses (results, n) produced from last run cell 

In [14]:
def drop_zero_rows(A): 
    return A[~np.all(A == 0, axis=1)]

In [15]:
from sympy import *          # Start using np arrays

A = np.array(results[0])      # results = [exponents_list, residues, iters, xsquares]
store_pows = A.copy()
A = (np.transpose(A))%2
print(A)

[[1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
 [1 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 1 1 0 0 1]
 [1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 

In [16]:
col_num = len(A[0])
row_num = len(A)
print("Old num rows and num columns: ", row_num, col_num)
L = Matrix(A)

L = np.array(L.rref()[0])      # reduced row echelon form
L2  = drop_zero_rows(L)        # get rid of primes we don't have to worry about in general
L2 = L2 %2

print("Reduced row echelon form AND mod 2 is: ")
print(L2)

print("New num rows, num columns: ", len(L2), len(L2[0]))

Old num rows and num columns:  25 26
Reduced row echelon form AND mod 2 is: 
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0

In [17]:
## Choose free variables:
def getA_solution(reduced_matrix):
    L = reduced_matrix
    col_num = len(L[0])
    row_num = len(L)
    v = np.ones(col_num, dtype = 'int')
    for i in reversed(range(row_num)):
        for j in reversed(range(col_num)):
            if L[i][j] ==1:
                #print("found row, col:", i, j, " with 1")
                if (L[i].sum()%2) !=0:              # the exponents for this prime doesn't add up to zero
                    v[j] = 0                  # can't use this equation
                    break     # no need to  check cells above, as reduced echelon form
    return(v)


In [18]:
v = getA_solution(L2)
print(v)

[0 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1]


In [25]:
def get_x_modN(xsq, n):    
    result = int(math.sqrt(xsq))%n
    return result

In [26]:
def get_xsq_modN(v, num_list):   # results = [exponents_list, residues, iters, xsquares]
    product= 1       
    for i in range(len(v)):
        if v[i] ==0:
            continue
        product = product * num_list[i]
#         product = product%n    # want the huge product sqrooted
    return product

In [27]:
residues = results[1]
xsquares = results[3]

print("residues, xquares: ", residues, xsquares)

ysq = get_xsq_modN(v, residues)     
xsq = get_xsq_modN(v, xsquares)   

y = get_x_modN(ysq, n)
x = get_x_modN(xsq, n)

print("final x square modN: ", xsq%n, " final y : ", ysq%n)     # just a check
if a_congruent_b(x, y, n):
    print("Oh no, x congruent y mod n!")

residues, xquares:  [38760, 17696, 52380, 53845, 70784, 36208, 9222, 73160, 35989, 129375, 59630, 165737, 163392, 122636, 73359, 74195, 186543, 99552, 144832, 43010, 122507, 34503, 99015, 175491, 214132, 5217] [383141476, 670447449, 1819790281, 2011343104, 2681789796, 3735287689, 6321204036, 6800146369, 8045193025, 8715716164, 9002973456, 9673509316, 9865058329, 10248120289, 11301603481, 12546688144, 13313005924, 14462227081, 14941150756, 15419927329, 15994660900, 16665002649, 19059459136, 19346862649, 19442676969, 19921346449]
final x square modN:  16183703  final y :  16183703


In [28]:
print(x, y)

61910944 92246193


In [29]:
k = math.gcd(x -int(y), n)
print(k)
print (int(n/k)) 

1
95775679
