In [48]:
import math
import numpy as np
import sympy
import time 

In [49]:
def calc_time(start, end):
    seconds = end - start
    mins = seconds / 60
    print('Time in seconds: ', str(seconds), ', Time in minutes: ', str(mins))
    return seconds, mins

In [50]:
# def gen_new_Bsmooth_candidates(primes, exponent_arr):
#     candidate_indices = np.where(x)
#     for i in range(len(primes)):
        

In [51]:
def get_multiples_sqrtN(multiple, s_const):
    return (multiple*s_const)**2 - n

In [52]:
def f(x):
    return (x+s_const)**2 - the_number

In [53]:
# Final optimized version 
def get_primes_less_thanB(bound):                      # eratosthenes way
    check_until = int(bound**0.5)
    unmarked = np.array([x for x in range(2, bound)])
    q = 2
    i = 0
    while True:
        u = unmarked[i]
        if u> check_until:               # only check numbers up to sqrt(bound)
            break
        u_idx = np.where(unmarked == u)[0][0]
        max_idx = bound//u
        listof_multiples = [u*i for i in range(q, max_idx+1)]
        u_multiples = np.array(listof_multiples)
        unmarked = np.setdiff1d(unmarked, u_multiples)   # numpy set diff without changing order of elements in list
        q = u
        i +=1
    print("Number of elements less than bound = ", bound, " is: ", len(unmarked))
    return (unmarked)

In [54]:
# Correct optimized version
def check_Bsmooth(primes, num):
    powers_of_primes= []
    num_remaining= num                         
    for prime in primes: 
        i = 0                                   # i = power of prime
        if (num_remaining%prime == 0):
            while (num_remaining%prime ==0):   #keep dividing for each power of the prime
                quotient = num_remaining/prime
                num_remaining = quotient
                i +=1
        powers_of_primes.append(i)
        if num_remaining == 1:     
            diff = len(primes)-len(powers_of_primes)
            if diff>0:
                zeros = [0 for k in range(diff)]
                return powers_of_primes + zeros
            return powers_of_primes
    #print("Number is not B smooth")
    return []

#### Start Choosing parameters for testing: bound, n, etc;

In [10]:
## I have kept the generator cell, but I generate more numbers in the next one. The prime number is set in this cell.
## bound is commented out, as it is already set, and the array of primes is already created

# n = 169214564391
# n = 12110279
# n = 62615533
n = 95775679
the_number = n
s_const = int(math.sqrt(n)) + 1
A_const = (math.sqrt(2)-1)*math.sqrt(n)-1      

print(A_const)

4052.703075635406


In [55]:
# A first simulation

bound = 50
primes = np.array(get_primes_less_thanB(bound))

Number of elements less than bound =  50  is:  15


In [32]:
def a_congruent_b(a, b, n):
    if a==(b%n):
        return True
    return False

In [28]:
a = 11
b = 911
print(a_congruent_b(a, b, 100))

True


In [58]:
def generate_squares(primes, n, multiple): # from which multiple do we want to start? can change this to coefficients later
    exponents_list = []
    residues = []          # (783)^2 = 2^9*11*13, residue = 2^9*11*13 mod n
    floor_sqrtN = int(math.sqrt(n)) + 1
    iterations = 0
    while(True):
        if iterations>10000:
            break
        candidate = (multiple*floor_sqrtN)**2 - n
        #print(candidate)
        exp_vec = check_Bsmooth(primes, candidate)
        if exp_vec!=[]:
            exp_arr = np.array(exp_vec)
            print(exp_arr)
            residue_vec = np.power(primes, exp_arr)
            print(residue_vec)
            pythlist = residue_vec.tolist()  # numpy leads to overflow, convert to python list again
            residue = 1
            for i in range(len(pythlist)):
                residue *= pythlist[i]
            residues.append(residue)
            exponents_list.append(exp_vec)
            print(residue)
            
        if len(residues)> len(primes) +3:
            print("Breaking, len of residues: ", len(residues), " len of primes: ", len(primes))
            break
        iterations +=1
        print("iterations: ", iterations)
        multiple +=1
    print("Returning, but why??")
    return [exponents_list, residues, iterations]
    

In [59]:
# Sample test of the function above
n = 95775679
multiple = 1
start = time.time()

results = generate_squares(primes, n, multiple)

calc_time(start, end)
end = time.time()
print("iterations, ", i)
print("B smooth numbers found: ", results[1], "total: ", len(results[1]))

[1 1 1 0 0 0 1 1 0 0 0 0 0 0 0]
[ 2  3  5  1  1  1 17 19  1  1  1  1  1  1  1]
9690
iterations:  1
iterations:  2
iterations:  3
iterations:  4
iterations:  5
iterations:  6
iterations:  7
iterations:  8
iterations:  9
iterations:  10
iterations:  11
iterations:  12
iterations:  13
iterations:  14
iterations:  15
iterations:  16
iterations:  17
iterations:  18
iterations:  19
iterations:  20
iterations:  21
iterations:  22
iterations:  23
iterations:  24
iterations:  25
iterations:  26
iterations:  27
iterations:  28
iterations:  29
iterations:  30
iterations:  31
iterations:  32
iterations:  33
iterations:  34
iterations:  35
iterations:  36
iterations:  37
iterations:  38
iterations:  39
iterations:  40
iterations:  41
iterations:  42
iterations:  43
iterations:  44
iterations:  45
iterations:  46
iterations:  47
iterations:  48
iterations:  49
iterations:  50
iterations:  51
iterations:  52
iterations:  53
iterations:  54
iterations:  55
iterations:  56
iterations:  57
iterations:  

iterations:  813
iterations:  814
iterations:  815
iterations:  816
iterations:  817
iterations:  818
iterations:  819
iterations:  820
iterations:  821
iterations:  822
iterations:  823
iterations:  824
iterations:  825
iterations:  826
iterations:  827
iterations:  828
iterations:  829
iterations:  830
iterations:  831
iterations:  832
iterations:  833
iterations:  834
iterations:  835
iterations:  836
iterations:  837
iterations:  838
iterations:  839
iterations:  840
iterations:  841
iterations:  842
iterations:  843
iterations:  844
iterations:  845
iterations:  846
iterations:  847
iterations:  848
iterations:  849
iterations:  850
iterations:  851
iterations:  852
iterations:  853
iterations:  854
iterations:  855
iterations:  856
iterations:  857
iterations:  858
iterations:  859
iterations:  860
iterations:  861
iterations:  862
iterations:  863
iterations:  864
iterations:  865
iterations:  866
iterations:  867
iterations:  868
iterations:  869
iterations:  870
iterations:  8

iterations:  1878
iterations:  1879
iterations:  1880
iterations:  1881
iterations:  1882
iterations:  1883
iterations:  1884
iterations:  1885
iterations:  1886
iterations:  1887
iterations:  1888
iterations:  1889
iterations:  1890
iterations:  1891
iterations:  1892
iterations:  1893
iterations:  1894
iterations:  1895
iterations:  1896
iterations:  1897
iterations:  1898
iterations:  1899
iterations:  1900
iterations:  1901
iterations:  1902
iterations:  1903
iterations:  1904
iterations:  1905
iterations:  1906
iterations:  1907
iterations:  1908
iterations:  1909
iterations:  1910
iterations:  1911
iterations:  1912
iterations:  1913
iterations:  1914
iterations:  1915
iterations:  1916
iterations:  1917
iterations:  1918
iterations:  1919
iterations:  1920
iterations:  1921
iterations:  1922
iterations:  1923
iterations:  1924
iterations:  1925
iterations:  1926
iterations:  1927
iterations:  1928
iterations:  1929
iterations:  1930
iterations:  1931
iterations:  1932
iterations

iterations:  2880
iterations:  2881
iterations:  2882
iterations:  2883
iterations:  2884
iterations:  2885
iterations:  2886
iterations:  2887
iterations:  2888
iterations:  2889
iterations:  2890
iterations:  2891
iterations:  2892
iterations:  2893
iterations:  2894
iterations:  2895
iterations:  2896
iterations:  2897
iterations:  2898
iterations:  2899
iterations:  2900
iterations:  2901
iterations:  2902
iterations:  2903
iterations:  2904
iterations:  2905
iterations:  2906
iterations:  2907
iterations:  2908
iterations:  2909
iterations:  2910
iterations:  2911
iterations:  2912
iterations:  2913
iterations:  2914
iterations:  2915
iterations:  2916
iterations:  2917
iterations:  2918
iterations:  2919
iterations:  2920
iterations:  2921
iterations:  2922
iterations:  2923
iterations:  2924
iterations:  2925
iterations:  2926
iterations:  2927
iterations:  2928
iterations:  2929
iterations:  2930
iterations:  2931
iterations:  2932
iterations:  2933
iterations:  2934
iterations

iterations:  3939
iterations:  3940
iterations:  3941
iterations:  3942
iterations:  3943
iterations:  3944
iterations:  3945
iterations:  3946
iterations:  3947
iterations:  3948
iterations:  3949
iterations:  3950
iterations:  3951
iterations:  3952
iterations:  3953
iterations:  3954
iterations:  3955
iterations:  3956
iterations:  3957
iterations:  3958
iterations:  3959
iterations:  3960
iterations:  3961
iterations:  3962
iterations:  3963
iterations:  3964
iterations:  3965
iterations:  3966
iterations:  3967
iterations:  3968
iterations:  3969
iterations:  3970
iterations:  3971
iterations:  3972
iterations:  3973
iterations:  3974
iterations:  3975
iterations:  3976
iterations:  3977
iterations:  3978
iterations:  3979
iterations:  3980
iterations:  3981
iterations:  3982
iterations:  3983
iterations:  3984
iterations:  3985
iterations:  3986
iterations:  3987
iterations:  3988
iterations:  3989
iterations:  3990
iterations:  3991
iterations:  3992
iterations:  3993
iterations

iterations:  5085
iterations:  5086
iterations:  5087
iterations:  5088
iterations:  5089
iterations:  5090
iterations:  5091
iterations:  5092
iterations:  5093
iterations:  5094
iterations:  5095
iterations:  5096
iterations:  5097
iterations:  5098
iterations:  5099
iterations:  5100
iterations:  5101
iterations:  5102
iterations:  5103
iterations:  5104
iterations:  5105
iterations:  5106
iterations:  5107
iterations:  5108
iterations:  5109
iterations:  5110
iterations:  5111
iterations:  5112
iterations:  5113
iterations:  5114
iterations:  5115
iterations:  5116
iterations:  5117
iterations:  5118
iterations:  5119
iterations:  5120
iterations:  5121
iterations:  5122
iterations:  5123
iterations:  5124
iterations:  5125
iterations:  5126
iterations:  5127
iterations:  5128
iterations:  5129
iterations:  5130
iterations:  5131
iterations:  5132
iterations:  5133
iterations:  5134
iterations:  5135
iterations:  5136
iterations:  5137
iterations:  5138
iterations:  5139
iterations

iterations:  5990
iterations:  5991
iterations:  5992
iterations:  5993
iterations:  5994
iterations:  5995
iterations:  5996
iterations:  5997
iterations:  5998
iterations:  5999
iterations:  6000
iterations:  6001
iterations:  6002
iterations:  6003
iterations:  6004
iterations:  6005
iterations:  6006
iterations:  6007
iterations:  6008
iterations:  6009
iterations:  6010
iterations:  6011
iterations:  6012
iterations:  6013
iterations:  6014
iterations:  6015
iterations:  6016
iterations:  6017
iterations:  6018
iterations:  6019
iterations:  6020
iterations:  6021
iterations:  6022
iterations:  6023
iterations:  6024
iterations:  6025
iterations:  6026
iterations:  6027
iterations:  6028
iterations:  6029
iterations:  6030
iterations:  6031
iterations:  6032
iterations:  6033
iterations:  6034
iterations:  6035
iterations:  6036
iterations:  6037
iterations:  6038
iterations:  6039
iterations:  6040
iterations:  6041
iterations:  6042
iterations:  6043
iterations:  6044
iterations

iterations:  6950
iterations:  6951
iterations:  6952
iterations:  6953
iterations:  6954
iterations:  6955
iterations:  6956
iterations:  6957
iterations:  6958
iterations:  6959
iterations:  6960
iterations:  6961
iterations:  6962
iterations:  6963
iterations:  6964
iterations:  6965
iterations:  6966
iterations:  6967
iterations:  6968
iterations:  6969
iterations:  6970
iterations:  6971
iterations:  6972
iterations:  6973
iterations:  6974
iterations:  6975
iterations:  6976
iterations:  6977
iterations:  6978
iterations:  6979
iterations:  6980
iterations:  6981
iterations:  6982
iterations:  6983
iterations:  6984
iterations:  6985
iterations:  6986
iterations:  6987
iterations:  6988
iterations:  6989
iterations:  6990
iterations:  6991
iterations:  6992
iterations:  6993
iterations:  6994
iterations:  6995
iterations:  6996
iterations:  6997
iterations:  6998
iterations:  6999
iterations:  7000
iterations:  7001
iterations:  7002
iterations:  7003
iterations:  7004
iterations

iterations:  8021
iterations:  8022
iterations:  8023
iterations:  8024
iterations:  8025
iterations:  8026
iterations:  8027
iterations:  8028
iterations:  8029
iterations:  8030
iterations:  8031
iterations:  8032
iterations:  8033
iterations:  8034
iterations:  8035
iterations:  8036
iterations:  8037
iterations:  8038
iterations:  8039
iterations:  8040
iterations:  8041
iterations:  8042
iterations:  8043
iterations:  8044
iterations:  8045
iterations:  8046
iterations:  8047
iterations:  8048
iterations:  8049
iterations:  8050
iterations:  8051
iterations:  8052
iterations:  8053
iterations:  8054
iterations:  8055
iterations:  8056
iterations:  8057
iterations:  8058
iterations:  8059
iterations:  8060
iterations:  8061
iterations:  8062
iterations:  8063
iterations:  8064
iterations:  8065
iterations:  8066
iterations:  8067
iterations:  8068
iterations:  8069
iterations:  8070
iterations:  8071
iterations:  8072
iterations:  8073
iterations:  8074
iterations:  8075
iterations

iterations:  9158
iterations:  9159
iterations:  9160
iterations:  9161
iterations:  9162
iterations:  9163
iterations:  9164
iterations:  9165
iterations:  9166
iterations:  9167
iterations:  9168
iterations:  9169
iterations:  9170
iterations:  9171
iterations:  9172
iterations:  9173
iterations:  9174
iterations:  9175
iterations:  9176
iterations:  9177
iterations:  9178
iterations:  9179
iterations:  9180
iterations:  9181
iterations:  9182
iterations:  9183
iterations:  9184
iterations:  9185
iterations:  9186
iterations:  9187
iterations:  9188
iterations:  9189
iterations:  9190
iterations:  9191
iterations:  9192
iterations:  9193
iterations:  9194
iterations:  9195
iterations:  9196
iterations:  9197
iterations:  9198
iterations:  9199
iterations:  9200
iterations:  9201
iterations:  9202
iterations:  9203
iterations:  9204
iterations:  9205
iterations:  9206
iterations:  9207
iterations:  9208
iterations:  9209
iterations:  9210
iterations:  9211
iterations:  9212
iterations

In [37]:
print("B smooth numbers found: ", results[1], "\ntotal: ", len(results[1]))

B smooth numbers found:  [3, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] total:  24


In [16]:
from sympy import *
np_array = np.array(results)
#A = Matrix(np_array)
#print(A)
print(np_array)
print(numbers)

[[1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 3 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [5 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 3 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 3 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 2 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [7 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 5 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 1 3 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 2 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [5 3 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 2 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 1 1 2 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 3 3 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [9 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 3 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 5 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [5 1 3 0 0 0 1 1 0 0 0 0 0 0 0

In [17]:
## store_pows is the original matrix of powers, which we use later in the computation of y
## We don't need to concatenate the 0 row

store_pows = np_array.copy()
matrixA = (np.transpose(np_array))%2
print(matrixA)
print("Number of rows, number of columns: ", len(matrixA), len(matrixA[0]))
# print(store_pows)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [19]:
def drop_zero_rows(A): 
    return A[~np.all(A == 0, axis=1)]

In [20]:
from sympy import *

col_num = len(matrixA[0])
row_num = len(matrixA)
print("Old num rows and num columns: ", row_num, col_num)
L = Matrix(matrixA)

aug_matrix = np.array(L.rref()[0])
aug_matrix  = drop_zero_rows(aug_matrix)
aug_matrix = aug_matrix %2

print("Reduced row echelon form AND mod 2 is: ")
print(aug_matrix)

print("New num rows, num columns: ", len(aug_matrix), len(aug_matrix[0]))

Old num rows and num columns:  24 28
Reduced row echelon form AND mod 2 is: 
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
New num rows, num columns:  1 28


In [22]:
v = aug_matrix[0]

In [19]:
# v: 0s are non-free variables, 1s are fixed variables which will be 1 (free or non-free),
# 2s are fixed variables which will be 0 (free or non-free)

v = np.ones(col_num, dtype = 'int')

row_num = len(aug_matrix)   # the row_num has changed after dropping the 0 rows
# find the leading entries, aka the non-free variables, set them to 0 in the v vector
for i in range(0, row_num):
    check_main = 1
    for j in range(i, col_num):
        if(aug_matrix[i][j]==1 and check_main ==1):
            v[j]=0
            break

print(v)

[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [23]:
print(v.sum())

28


In [ ]:
for i in range(len(store_pows)):
    
    newnum = np.multiply()

In [20]:
# set one of the free variable to 1, all the rest of the free variables to 2.
## THIS IS A HUGE PLACE FOR OPTIMIZATION, IF WE PICK THE RIGHT FREE VARIABLE LIFE WILL BE EASIER LATER

delete_ones = False
for i in range(0, col_num):
    if(delete_ones==True and v[i]==1):
        v[i]=2
    if(v[i]==1):
        delete_ones = True

print(v)

[0 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [3]:
a = np.array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1])
first = np.where(a==1)
print(first)
a[a==1] = 2
a[first] = 1
print(a)

[1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1]


In [21]:
# Optimized with numpy

for i in reversed(range(0, row_num)):
    sum = np.multiply(v, aug_matrix[i]).sum()        # equal to sum = sum + sum + v[j]*aug_matrix[i][j] for all j
    sum = sum%2;
    zer =(np.argwhere(v == 0).flatten())
    if(len(zer)!=0):
        index = zer[len(zer)-1]   # last entry
        if(sum==0):
            v[index] = 2
        else:
            v[index] = 1
        
print("final v vector is ", v%2)
        

final v vector is  [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [22]:
# optimized with numpy

v = v%2
print(len(v))
x = np.multiply(nums, v)     # element-wise multiplication of two arrays
print(x)
x[x==0] = 1
x = np.prod(x)      # prod is essentially multiplying elements of an array together
print(x)

28


ValueError: operands could not be broadcast together with shapes (0,) (28,) 

In [23]:
y_v  = np.zeros(size_of_bound)
indices = np.argwhere(v==1)[0]
print(indices)
print(store_pows)
store_pows = store_pows[indices]
print(store_pows)


[0]
[[1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 3 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [5 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 3 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 3 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 2 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [7 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 5 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 1 3 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 2 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [5 3 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 2 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 1 1 2 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 3 3 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [9 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 3 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 5 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [5 1 3 0 0 0 1 1 0 0 0 0 0

In [24]:
for row in store_pows:
    y_v = np.add(y_v, row)

y_v = y_v/2
print("y_v: ", y_v)

y = 1
z = np.power(primes, y_v)
print(z)
y = y*z


y = np.prod(y)   # no need to check y_v == 0, since anything raised to 0 is 1, and on multiplication, 1 has no effect
    
print("x is ", x, ", y is ", y)

y_v:  [0.5 0.5 0.5 0.  0.  0.  0.5 0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0. ]
[1.41421356 1.73205081 2.23606798 1.         1.         1.
 4.12310563 4.35889894 1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.        ]


NameError: name 'x' is not defined

In [20]:
k = math.gcd(x -int(y), the_number)
print(k)
print (int(the_number/k)) 

1
95775679
