In [2]:
import math
import numpy as np
import sympy
import time 

In [3]:
def calc_time(start, end):
    seconds = end - start
    mins = seconds / 60
    print('Time:', str(seconds), '    ', str(mins))
    return seconds, mins

In [5]:
# def gen_new_Bsmooth_candidates(primes, exponent_arr):
#     candidate_indices = np.where(x)
#     for i in range(len(primes)):
        

In [6]:
def get_multiples_sqrtN(multiple, s_const):
    return (multiple*s_const)**2 - n

In [7]:
def f(x):
    return (x+s_const)**2 - the_number

In [8]:
# Final optimized version 
def get_primes_less_thanB(bound):                      # eratosthenes way
    check_until = int(bound**0.5)
    unmarked = np.array([x for x in range(2, bound)])
    q = 2
    i = 0
    while True:
        u = unmarked[i]
        if u> check_until:               # only check numbers up to sqrt(bound)
            break
        u_idx = np.where(unmarked == u)[0][0]
        max_idx = bound//u
        listof_multiples = [u*i for i in range(q, max_idx+1)]
        u_multiples = np.array(listof_multiples)
        unmarked = np.setdiff1d(unmarked, u_multiples)   # numpy set diff without changing order of elements in list
        q = u
        i +=1
    print("Number of elements less than bound = ", bound, " is: ", len(unmarked))
    return (unmarked)

In [9]:
# Correct optimized version
def check_Bsmooth(primes, num):
    powers_of_primes= []
    num_remaining= num                         
    for prime in primes: 
        i = 0                                   # i = power of prime
        if (num_remaining%prime == 0):
            while (num_remaining%prime ==0):   #keep dividing for each power of the prime
                quotient = num_remaining/prime
                num_remaining = quotient
                i +=1
        powers_of_primes.append(i)
        if num_remaining == 1:     
            diff = len(primes)-len(powers_of_primes)
            if diff>0:
                zeros = [0 for k in range(diff)]
                return powers_of_primes + zeros
            return powers_of_primes
    #print("Number is not B smooth")
    return []

#### Start Choosing parameters for testing: bound, n, etc;

In [10]:
## I have kept the generator cell, but I generate more numbers in the next one. The prime number is set in this cell.
## bound is commented out, as it is already set, and the array of primes is already created

# n = 169214564391
# n = 12110279
# n = 62615533
n = 95775679
the_number = n
s_const = int(math.sqrt(n)) + 1
A_const = (math.sqrt(2)-1)*math.sqrt(n)-1      

print(A_const)

4052.703075635406


In [11]:
# A first simulation

bound = 90
primes = np.array(get_primes_less_thanB(bound))

Number of elements less than bound =  90  is:  24


In [32]:
def a_congruent_b(a, b, n):
    if a==(b%n):
        return True
    return False

In [28]:
a = 11
b = 911
print(a_congruent_b(a, b, 100))

True


In [38]:
def generate_squares(primes, n, multiple): # from which multiple do we want to start? can change this to coefficients later
    exponents_list = []
    residues = []          # (783)^2 = 2^9*11*13, residue = 2^9*11*13 mod n
    floor_sqrtN = int(math.sqrt(n)) + 1
    iterations = 0
    while(True):
        if iterations>10000:
            break
        candidate = (multiple*floor_sqrtN)**2 - n
        #candidatemodN = candidate%n
#         if a_congruent_b(candidate, candidate, n):    # ignore if x^2 '=' y^2 mod n, but x '=' +- y mod n
#             continue
        exp_vec = check_Bsmooth(primes, candidate)
        if exp_vec!=[]:
            exp_arr = np.array(exp_vec)
            residue_vec = np.power(primes, exp_arr)
            pythlist = residue_vec.tolist()  # numpy leads to overflow, convert to python list again
            residue = 1
            for i in range(len(pythlist)):
                residue *= pythlist[i]
            residues.append(residue)
            exponents_list.append(exp_vec)

        if len(residues)> len(primes) +3:
            break
        iterations +=1
        multiple +=1

    return [exponents_list, residues, iterations]
    

In [39]:
# Sample test of the function above
n = 95775679
multiple = 1
start = time.time()

results = generate_squares(primes, n, multiple)

calc_time(start, end)
end = time.time()
print("iterations, ", i)
print("B smooth numbers found: ", results[1], "total: ", len(results[1]))

Time: -22129.97998046875      -368.83299967447914
iterations,  27
B smooth numbers found:  [9690] total:  1


In [37]:
print("B smooth numbers found: ", results[1], "total: ", len(results[1]))

B smooth numbers found:  [3, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] total:  24


In [16]:
from sympy import *
np_array = np.array(results)
#A = Matrix(np_array)
#print(A)
print(np_array)
print(numbers)

[[1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 3 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [5 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 3 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 3 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 2 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [7 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 5 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 1 3 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 2 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [5 3 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 2 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 1 1 2 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 3 3 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [9 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 3 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 5 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [5 1 3 0 0 0 1 1 0 0 0 0 0 0 0

In [17]:
## store_pows is the original matrix of powers, which we use later in the computation of y
## We don't need to concatenate the 0 row

store_pows = np_array.copy()
matrixA = (np.transpose(np_array))%2
print(matrixA)
print("Number of rows, number of columns: ", len(matrixA), len(matrixA[0]))
# print(store_pows)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [19]:
def drop_zero_rows(A): 
    return A[~np.all(A == 0, axis=1)]

In [20]:
from sympy import *

col_num = len(matrixA[0])
row_num = len(matrixA)
print("Old num rows and num columns: ", row_num, col_num)
L = Matrix(matrixA)

aug_matrix = np.array(L.rref()[0])
aug_matrix  = drop_zero_rows(aug_matrix)
aug_matrix = aug_matrix %2

print("Reduced row echelon form AND mod 2 is: ")
print(aug_matrix)

print("New num rows, num columns: ", len(aug_matrix), len(aug_matrix[0]))

Old num rows and num columns:  24 28
Reduced row echelon form AND mod 2 is: 
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
New num rows, num columns:  1 28


In [22]:
v = aug_matrix[0]

In [19]:
# v: 0s are non-free variables, 1s are fixed variables which will be 1 (free or non-free),
# 2s are fixed variables which will be 0 (free or non-free)

v = np.ones(col_num, dtype = 'int')

row_num = len(aug_matrix)   # the row_num has changed after dropping the 0 rows
# find the leading entries, aka the non-free variables, set them to 0 in the v vector
for i in range(0, row_num):
    check_main = 1
    for j in range(i, col_num):
        if(aug_matrix[i][j]==1 and check_main ==1):
            v[j]=0
            break

print(v)

[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [23]:
print(v.sum())

28


In [ ]:
for i in range(len(store_pows)):
    
    newnum = np.multiply()

In [20]:
# set one of the free variable to 1, all the rest of the free variables to 2.
## THIS IS A HUGE PLACE FOR OPTIMIZATION, IF WE PICK THE RIGHT FREE VARIABLE LIFE WILL BE EASIER LATER

delete_ones = False
for i in range(0, col_num):
    if(delete_ones==True and v[i]==1):
        v[i]=2
    if(v[i]==1):
        delete_ones = True

print(v)

[0 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [3]:
a = np.array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1])
first = np.where(a==1)
print(first)
a[a==1] = 2
a[first] = 1
print(a)

[1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1]


In [21]:
# Optimized with numpy

for i in reversed(range(0, row_num)):
    sum = np.multiply(v, aug_matrix[i]).sum()        # equal to sum = sum + sum + v[j]*aug_matrix[i][j] for all j
    sum = sum%2;
    zer =(np.argwhere(v == 0).flatten())
    if(len(zer)!=0):
        index = zer[len(zer)-1]   # last entry
        if(sum==0):
            v[index] = 2
        else:
            v[index] = 1
        
print("final v vector is ", v%2)
        

final v vector is  [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [22]:
# optimized with numpy

v = v%2
print(len(v))
x = np.multiply(nums, v)     # element-wise multiplication of two arrays
print(x)
x[x==0] = 1
x = np.prod(x)      # prod is essentially multiplying elements of an array together
print(x)

28


ValueError: operands could not be broadcast together with shapes (0,) (28,) 

In [23]:
y_v  = np.zeros(size_of_bound)
indices = np.argwhere(v==1)[0]
print(indices)
print(store_pows)
store_pows = store_pows[indices]
print(store_pows)


[0]
[[1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 3 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [5 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 3 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 3 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 2 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [7 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 5 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 1 3 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 2 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [5 3 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 2 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 1 1 2 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 3 3 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [9 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 3 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [3 5 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [5 1 3 0 0 0 1 1 0 0 0 0 0

In [24]:
for row in store_pows:
    y_v = np.add(y_v, row)

y_v = y_v/2
print("y_v: ", y_v)

y = 1
z = np.power(primes, y_v)
print(z)
y = y*z


y = np.prod(y)   # no need to check y_v == 0, since anything raised to 0 is 1, and on multiplication, 1 has no effect
    
print("x is ", x, ", y is ", y)

y_v:  [0.5 0.5 0.5 0.  0.  0.  0.5 0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0. ]
[1.41421356 1.73205081 2.23606798 1.         1.         1.
 4.12310563 4.35889894 1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.        ]


NameError: name 'x' is not defined

In [20]:
k = math.gcd(x -int(y), the_number)
print(k)
print (int(the_number/k)) 

1
95775679
