In [1]:
import math
import numpy as np
import sympy
import time 

In [2]:
def calc_time(start, end):
    seconds = end - start
    mins = seconds / 60
    print('Time:', str(seconds), '    ', str(mins))
    return seconds, mins

In [21]:
## I have kept the generator cell, but I generate more numbers in the next one. The prime number is set in this cell.
## bound is commented out, as it is already set, and the array of primes is already created

# n = 16921456439215439701
# n = 12110279
n = 62615533
the_number = n
s_const = int(math.sqrt(n)) + 1
A_const = (math.sqrt(2)-1)*math.sqrt(n)-1      

print(A_const)

3276.67097683093


In [4]:
def f(x):
    return (x+s_const)**2 - the_number

In [5]:
# Final optimized version 
def get_primes_less_thanB(bound):                      # eratosthenes way
    check_until = int(bound**0.5)
    unmarked = np.array([x for x in range(2, bound)])
    q = 2
    i = 0
    while True:
        u = unmarked[i]
        if u> check_until:               # only check numbers up to sqrt(bound)
            break
        u_idx = np.where(unmarked == u)[0][0]
        max_idx = bound//u
        listof_multiples = [u*i for i in range(q, max_idx+1)]
        u_multiples = np.array(listof_multiples)
        unmarked = np.setdiff1d(unmarked, u_multiples)   # numpy set diff without changing order of elements in list
        q = u
        i +=1
    print("Number of elements less than bound = ", bound, " is: ", len(unmarked))
    return (unmarked)

In [6]:
# Correct optimized version
def check_Bsmooth(primes, num):
    powers_of_primes= []
    num_remaining= num                         
    for prime in primes: 
        i = 0                                   # i = power of prime
        if (num_remaining%prime == 0):
            while (num_remaining%prime ==0):   #keep dividing for each power of the prime
                quotient = num_remaining/prime
                num_remaining = quotient
                i +=1
        powers_of_primes.append(i)
        if num_remaining == 1:     
            diff = len(primes)-len(powers_of_primes)
            if diff>0:
                zeros = [0 for k in range(diff)]
                return powers_of_primes + zeros
            return powers_of_primes
    #print("Number is not B smooth")
    return []

#### Start Choosing parameters for testing: bound, n, etc;

In [9]:
# A first simulation
n = 62615533
bound = 40
primes = np.array(get_primes_less_thanB(bound))

Number of elements less than bound =  40  is:  12


In [10]:
## this is the generator cell, it works for the small tests I am doing, but we will have to update it later
nums = []
results=[]
size_of_bound = len(primes)

numbers = []
count_found = 0
begin = int(math.sqrt(n)) + 1
i = 0
start = time.time()
while(True):
    temp = check_Bsmooth(primes, (begin**2)%n)
    if temp!=[]:
        exponents = np.array(temp)
        result = np.power(primes, exponents)
        the_num = np.prod(result)
        numbers.append(the_num)
        
        nums.append(begin)
        results.append(temp)
        count_found = count_found +1
            
    if count_found> size_of_bound +3:
        break
    begin +=1
    i +=1
end = time.time()
print("iterations, ", i)
print("B smooth numbers found: ", numbers, "total: ", len(numbers))
calc_time(start, end)
print (results)

iterations,  11368
B smooth numbers found:  [36, 937251, 22521996, 34781628, 119350, 455455, 859375, 1691690, 41204735, 144, 3749004, 35360, 16344835, 27287936, 47580416, 58679296] total:  16
Time: 0.3793299198150635      0.006322165330251058
[[2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 5, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0], [2, 3, 0, 1, 0, 0, 0, 0, 0, 0, 3, 0], [2, 1, 0, 1, 0, 0, 0, 2, 0, 0, 1, 1], [1, 0, 2, 1, 1, 0, 0, 0, 0, 0, 1, 0], [0, 0, 1, 2, 1, 2, 0, 0, 0, 0, 0, 0], [0, 0, 7, 0, 1, 0, 0, 0, 0, 0, 0, 0], [1, 0, 1, 1, 1, 3, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 2, 3, 0, 0, 0, 0, 1, 0], [4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 5, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0], [5, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 2, 0, 0, 1, 2, 0, 0], [7, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0], [8, 0, 0, 0, 0, 1, 1, 0, 0, 2, 0, 0], [13, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0]]


In [11]:
## store_pows is the original matrix of powers, which we use later in the computation of y
## We don't need to concatenate the 0 row

np_array = np.array(results)
store_pows = np_array.copy()

matrixA = (np.transpose(np_array))%2
print(matrixA)
print("Number of rows, number of columns: ", len(matrixA), len(matrixA[0]))
# print(store_pows)

[[0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 1]
 [0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0]
 [0 1 1 1 1 0 0 1 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 1 0 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1]
 [0 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]]
Number of rows, number of columns:  12 16


In [12]:
def drop_zero_rows(A): 
    return A[~np.all(A == 0, axis=1)]

In [13]:
from sympy import *

col_num = len(matrixA[0])
row_num = len(matrixA)
L = Matrix(matrixA)

aug_matrix = np.array(L.rref()[0])
aug_matrix  = drop_zero_rows(aug_matrix)

print("Reduced row echelon form is: ")
print(aug_matrix)

print("Number of rows, number of columns: ", len(aug_matrix), len(aug_matrix[0]))

Reduced row echelon form is: 
[[0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 -1]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]]
Number of rows, number of columns:  11 16


In [14]:
# v: 0s are non-free variables, 1s are fixed variables which will be 1 (free or non-free),
# 2s are fixed variables which will be 0 (free or non-free)

v = np.ones(col_num, dtype = 'int')

row_num = len(aug_matrix)   # the row_num has changed after dropping the 0 rows
# find the leading entries, aka the non-free variables, set them to 0 in the v vector
for i in range(0, row_num):
    check_main = 1
    for j in range(i, col_num):
        if(aug_matrix[i][j]==1 and check_main ==1):
            v[j]=0
            break

print(v)

[1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1]


In [15]:
# set one of the free variable to 1, all the rest of the free variables to 2.
## THIS IS A HUGE PLACE FOR OPTIMIZATION, IF WE PICK THE RIGHT FREE VARIABLE LIFE WILL BE EASIER LATER

delete_ones = False
for i in range(0, col_num):
    if(delete_ones==True and v[i]==1):
        v[i]=2
    if(v[i]==1):
        delete_ones = True

print(v)

[1 0 0 0 0 0 2 0 0 2 2 0 0 0 0 2]


In [16]:
# Optimized with numpy

for i in reversed(range(0, row_num)):
    sum = np.multiply(v, aug_matrix[i]).sum()        # equal to sum = sum + sum + v[j]*aug_matrix[i][j] for all j
    sum = sum%2;
    zer =(np.argwhere(v == 0).flatten())
    if(len(zer)!=0):
        index = zer[len(zer)-1]   # last entry
        if(sum==0):
            v[index] = 2
        else:
            v[index] = 1
        
print("final v vector is ", v%2)
        

final v vector is  [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [17]:
# optimized with numpy

v = v%2
print(len(v))
x = np.multiply(nums, v)     # element-wise multiplication of two arrays
print(x)
x[x==0] = 1
x = np.prod(x)      # prod is essentially multiplying elements of an array together
print(x)

16
[7913    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0]
7913


In [18]:
y_v  = np.zeros(size_of_bound)
indices = np.argwhere(v==1)[0]
print(indices)
print(store_pows)
store_pows = store_pows[indices]
print(store_pows)


[0]
[[ 2  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  0  1  0  0  0  1  0  1  0  0]
 [ 2  3  0  1  0  0  0  0  0  0  3  0]
 [ 2  1  0  1  0  0  0  2  0  0  1  1]
 [ 1  0  2  1  1  0  0  0  0  0  1  0]
 [ 0  0  1  2  1  2  0  0  0  0  0  0]
 [ 0  0  7  0  1  0  0  0  0  0  0  0]
 [ 1  0  1  1  1  3  0  0  0  0  0  0]
 [ 0  0  1  0  2  3  0  0  0  0  1  0]
 [ 4  2  0  0  0  0  0  0  0  0  0  0]
 [ 2  5  0  1  0  0  0  1  0  1  0  0]
 [ 5  0  1  0  0  1  1  0  0  0  0  0]
 [ 0  0  1  0  0  2  0  0  1  2  0  0]
 [ 7  0  0  0  0  1  0  0  2  0  1  0]
 [ 8  0  0  0  0  1  1  0  0  2  0  0]
 [13  0  0  0  0  1  0  1  0  1  0  0]]
[[2 2 0 0 0 0 0 0 0 0 0 0]]


In [19]:
for row in store_pows:
    y_v = np.add(y_v, row)

y_v = y_v/2
print("y_v: ", y_v)

y = 1
z = np.power(primes, y_v)
print(z)
y = y*z


y = np.prod(y)   # no need to check y_v == 0, since anything raised to 0 is 1, and on multiplication, 1 has no effect
    
print("x is ", x, ", y is ", y)

y_v:  [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
x is  7913 , y is  6.0


In [22]:
k = math.gcd(x -int(y), the_number)
print(k)
print (int(the_number/k)) 

7907
7919
