I got quite frustrated about the Gaussian elimination. I don't understand what others were exactly doing,
 but solving Ax=0 when rank(A) is smaller than #rows in matrix A seems to be almost always solved by the 
 method of 'inspection', in the resources I found online.
 Hence, I decided to assume we will generate a square matrix for now

In [341]:
# got rid of the inefficiency of last time
def get_primes_less_thanB(bound):                      # eratosthenes way
    start = 2
    unmarked = set([x for x in range(bound)])
    unmarked.remove(0)
    unmarked.remove(1)
    repeat_list = []
    q = 2
    i = 0
    while True:
        u = list(unmarked)[i]
        print("In this iteration, u = ", u)
        if u> int(bound**0.5):               # only check numbers up to sqrt(bound)
            break
        while u*q<= bound:
            repeat_list.append(u*q)
            unmarked = unmarked - set(repeat_list)
            q+=1
        q = 2
        i +=1
        print("Elements still unmarked: ", unmarked)
    return (list(unmarked))

In [342]:
bound = 18
primes = get_primes_less_thanB(bound)

In this iteration, u =  2
Elements still unmarked:  {2, 3, 5, 7, 9, 11, 13, 15, 17}
In this iteration, u =  3
Elements still unmarked:  {2, 3, 5, 7, 11, 13, 17}
In this iteration, u =  5


In [343]:
def check_Bsmooth(num, bound):
    ## I commented out this line, because we don't need to compute the primes every time,
    ## instead we can compute once, and then use the same array
    
    #primes_less_thanB = get_primes_less_thanB(bound)
    
    powers_of_primes= []
    num_remaining= num                          # keep dividing by primes in B smooth primes, until == 1
    for prime in primes:#_less_thanB:
        i = 0                                   # i = power of prime
        if (num_remaining%prime == 0):
            while (num_remaining%prime ==0):   #keep dividing for each power of the prime
                quotient = num_remaining/prime
                num_remaining = quotient
                i +=1
        powers_of_primes.append(i)
    if num_remaining == 1:
        print("Number is B smooth, using primes:", primes, "with corresponding powers:", powers_of_primes)
        return powers_of_primes
    print("Number is not B smooth")
    return []



In [344]:
# Some tests
#bound = 7
## I have kept the generator cell, but I generate more numbers in the next one. The prime number is set in this cell.
## bound is commented out, as it is already set, and the array of primes is already created

n = 2257
num1 =  (439**2)%n
num2 = (444**2)%n
num3 = (445**2)%n
num4 = (447**2)%n
num5 = (449**2)%n
num6 = ()

result1 = check_Bsmooth(num1, bound)
result2 = check_Bsmooth(num2, bound)
result3 = check_Bsmooth(num3, bound)
result4 = check_Bsmooth(num4, bound)
result5 = check_Bsmooth(num5, bound)

results = [result1, result2, result3, result4, result5]

## the_number is used later in the gcd computation
the_number = n

Number is not B smooth
Number is not B smooth
Number is B smooth, using primes: [2, 3, 5, 7, 11, 13, 17] with corresponding powers: [1, 0, 0, 2, 0, 0, 1]
Number is not B smooth
Number is B smooth, using primes: [2, 3, 5, 7, 11, 13, 17] with corresponding powers: [3, 0, 0, 1, 0, 1, 0]


In [345]:
## this is the generator cell, it works for the small tests I am doing, but we will have to update it later
nums =[]
results=[]
for i in range(75, 200):
    temp= check_Bsmooth((i**2)%n, bound)
    if temp!=[]:
        nums.append(i)
        results.append(temp)
print (results)

Number is not B smooth
Number is not B smooth
Number is not B smooth
Number is not B smooth
Number is not B smooth
Number is not B smooth
Number is not B smooth
Number is B smooth, using primes: [2, 3, 5, 7, 11, 13, 17] with corresponding powers: [1, 0, 1, 0, 0, 1, 1]
Number is not B smooth
Number is not B smooth
Number is not B smooth
Number is B smooth, using primes: [2, 3, 5, 7, 11, 13, 17] with corresponding powers: [0, 0, 4, 0, 0, 0, 0]
Number is not B smooth
Number is not B smooth
Number is not B smooth
Number is not B smooth
Number is not B smooth
Number is not B smooth
Number is not B smooth
Number is not B smooth
Number is not B smooth
Number is not B smooth
Number is not B smooth
Number is B smooth, using primes: [2, 3, 5, 7, 11, 13, 17] with corresponding powers: [6, 2, 0, 0, 0, 0, 0]
Number is not B smooth
Number is B smooth, using primes: [2, 3, 5, 7, 11, 13, 17] with corresponding powers: [2, 5, 0, 0, 0, 0, 0]
Number is not B smooth
Number is not B smooth
Number is not B 

In [346]:
# Using numpy
import numpy as np
# import geopandas as gpd

matrix = []
for result in results:
    if result != "[]":
        matrix.append(result)
np_array = np.array(matrix)

## store_pows is the original matrix of powers, which we use later in the computation of y

store_pows = np_array
np_array = np.transpose(np_array)
print(np_array %2)




[[1 0 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 1 0 0 0 0]
 [1 0 0 0 0 0 0 1 1 1 1 0 1 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1]
 [0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1]
 [1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0]]


In [347]:
import numpy.linalg
a = (np_array%2)
n = len(a)            # row number + number of equations we have
m = len(a[0])        # column number + number of primes (in factor base)

b =  np.array([[0 for i in range(n)]])     # all zeros
# r = np.array([[i] for i in range(n)])
a = np.concatenate((a, b.T), axis=1)
# a = np.concatenate((a, r.T), axis=1)
print(a)

[[1 0 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 1 1 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1 0]
 [1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0]]


In [348]:
# changed it to remove all zero rows from A
def zero_row(A): 
    return A[~np.all(A == 0, axis=1)]

In [349]:
## I have commented out most of the print statements, since for a large matrix the print output is a lot, but
## they can be used in further debugging.

## The only thing I changed about the function is that instead of returning rows and cols upon finding an 0 row, the zero row
## function removes all zero rows, and then the function returns the augmented matrix, so we can continu working with it.


def upp_triangular(num_rows, num_cols, aug_matA):
    A = aug_matA
    n = num_rows
    m = num_cols
    row_adds = []
    swaps = []
    for i in range(m):            # column
        if i>=n:    
            break
        #print("row num: ", i)
        A = A%2
        #print("current matrix ", A)
        maxi = i
        for k in range(i, n):                 # first row at i or below where entry is 1 - pivot for that column
            if A[k][i] ==1:
                maxi = k
                break
        #print("finished looping through rows")
        if A[maxi][i] != 1:                    # no '1'- entry in any row for this column
        #    print("No pivots in this column")
            continue
        else:                                 # some row = maxi row has a 1 entry
        #    print("found a row with a 1 entry, which is: row ", maxi)
            if maxi != i:            # need to swap rows
        #        print ("Swapping rows for row = ", i, "and maxi = ", maxi)
                currenti = A[i].copy()
                A[i] = A[maxi]
                A[maxi] = currenti
        #        print("matrix overall after swap: ", A)
                swaps.append((i,maxi))
            for j in range(i+1, n):    # check every entry directly below A[i][i] 
                belowi = A[j][i]
        #        print("belowi: ", belowi)
                if belowi !=0:          # if entry is 1 for any row, nullify it
                    A[j]+= A[i]
                    row_adds.append((i,j))
        #            print("belowi non zero: ", belowi, "for row = ", j)
        #            print("A[j] after adding row A[i] to it", A[j])
    
    # should have upper triangular matrix at the end of this 
    A =zero_row(A)
           # print('mama')
            #return (swaps, row_adds)
    #for action in all_actions:
    #    print(action)
    #for tup in whichRow_addedto_which:
    #    print(tup)
    return A
    


In [350]:
aug_matrix = a
row_num = len(a)
col_num = len(a[0])

aug_matrix = upp_triangular(row_num, col_num,  aug_matrix)

print("reduced row echelon form is ")
print(aug_matrix)

# v: 0s are non-free variables, 1s are fixed variables which will be 1 (free or non-free),
# 2s are fixed variables which will be 0 (free or non-free)

v = np.ones(col_num, dtype = 'int')

# the row_num has changed after dropping the 0 rows
row_num = len(aug_matrix)

# find the leading entries, aka the non-free variables, set them to 0 in the v vector
for i in range(0, row_num):
    check_main = 1
    for j in range(0, col_num):
        if(aug_matrix[i][j]==1 and check_main ==1):
            v[j]=0
            break

# set one of the free variable to 1, all the rest of the free variables to 2.
## THIS IS A HUGE PLACE FOR OPTIMIZATION, IF WE PICK THE RIGHT FREE VARIABLE LIFE WILL BE EASIER LATER

delete_ones=False
for i in range(0, col_num):
    if(delete_ones==True and v[i]==1):
        v[i]=2
    if(v[i]==1):
        delete_ones = True
            
# calculate the other variables according to the values of the free variables we have:

for i in reversed(range(0, row_num)):
    #for j in range(0, col_num):
    sum =0
    for j in range(0, col_num):
        sum = sum + v[j]*aug_matrix[i][j];
    zer =(np.argwhere(v == 0).flatten())
    sum = sum%2;
    if(len(zer)!=0):
        index = zer[len(zer)-1]
    
        if(sum==0):
            v[index] = 2
        else:
            v[index] = 1
        
print("v vector is ", v%2)
        
x = 1;
y = int(1);

for i in range(0, col_num):
    if v[i] ==1:
        x = x * nums[i]
        for j in range(0, len(primes)):
            if(store_pows[i][j]!=0):
                #print(int(y*(primes[j]**store_pows[i][j])))
                y = (y* ((primes[j]**store_pows[i][j])))

print("x is ", x, ", y is ", y)


reduced row echelon form is 
[[1 0 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1 0]
 [0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0]]
v vector is  [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
x is  86 , y is  625


In [351]:
import math

## another possible optimization is to add the powers and divide them by two, instead of multiplying out a very large number
## and squaring it later.

k = math.gcd(int(math.sqrt(y)) - x, the_number)
print(k)
print (the_number/k) 

61
37.0


In [352]:
### MATRIX NOT IN RRE DOESN'T MEAN THE REST IS TRUE, IT IS THE FIRST
### CHECKPOINT WHERE THE ALGO FAILS, I HAVE TO TEST IT OUT FIRTHER

### works for 5429 = 61*89
### doesn't work for 8633 = 89 * 97 - matrix not in RRE
### doesn't work for 8051 = 83 *97 - the matrix is not in reduced echelon form
### works for 2257 = 61*37