In [477]:
import math
import numpy as np
import sympy
import time 

In [478]:
def calc_time(start, end):
    seconds = end - start
    mins = seconds / 60
    print('Time:', str(seconds), '    ', str(mins))
    return seconds

In [479]:
def f(x):
    return (x+s_const)**2 - the_number

In [480]:
# Final optimized version 
def get_primes_less_thanB(bound):                      # eratosthenes way
    check_until = int(bound**0.5)
    unmarked = np.array([x for x in range(2, bound)])
    q = 2
    i = 0
    while True:
        u = unmarked[i]
        if u> check_until:               # only check numbers up to sqrt(bound)
            break
        u_idx = np.where(unmarked == u)[0][0]
        max_idx = bound//u
        listof_multiples = [u*i for i in range(q, max_idx+1)]
        u_multiples = np.array(listof_multiples)
        unmarked = np.setdiff1d(unmarked, u_multiples)   # numpy set diff without changing order of elements in list
        q = u
        i +=1
    print("Number of elements less than bound = ", bound, " is: ", len(unmarked))
    return (unmarked)

In [481]:
# Correct optimized version
def check_Bsmooth(primes, num):
    powers_of_primes= []
    num_remaining= num                         
    for prime in primes: 
        i = 0                                   # i = power of prime
        if (num_remaining%prime == 0):
            while (num_remaining%prime ==0):   #keep dividing for each power of the prime
                quotient = num_remaining/prime
                num_remaining = quotient
                i +=1
        powers_of_primes.append(i)
        if num_remaining == 1:     
            diff = len(primes)-len(powers_of_primes)
            if diff>0:
                zeros = [0 for k in range(diff)]
                return powers_of_primes + zeros
            return powers_of_primes
    #print("Number is not B smooth")
    return []

#### Start Choosing parameters for testing: bound, n, etc;

In [482]:
## Input the number n in this cell:

begin_time = time.time()
#n = 1043302887923
n = 169214564391

the_number = n
s_const = int(math.sqrt(n)) + 1
A_const = (math.sqrt(2)-1)*math.sqrt(n)-1      

print(A_const)

170388.63978888164


In [483]:
# Calculation of the boundary

k = math.log(n)
k = k*math.log(k)
k = math.exp(math.sqrt(k))
k = math.pow(k, math.sqrt(2)/4)

bound = int(k)
print(bound)
primes = np.array(get_primes_less_thanB(bound))

25
Number of elements less than bound =  25  is:  9


In [484]:
## this is the generator cell, it works for the small tests I am doing, but we will have to update it later
nums = []
results=[]
size_of_bound = len(primes)

numbers = []
count_found = 0
begin = int(math.sqrt(n)) + 1
i = 0
start = time.time()
while(True):
    temp = check_Bsmooth(primes, (begin**2)%n)
    if temp!=[]:
        exponents = np.array(temp)
        result = np.power(primes, exponents)
        the_num = np.prod(result)
        numbers.append(the_num)
        
        nums.append(begin)
        results.append(temp)
        count_found = count_found +1
            
    if count_found> size_of_bound +3:
        break
    begin +=1
    i +=1
end = time.time()
print("iterations, ", i)
print("B smooth numbers found: ", numbers, "total: ", len(numbers))
calc_time(start, end)
print (results)

iterations,  4175629
B smooth numbers found:  [-441954548, -1637079905, -1767818192, 1112832464, 1243146929, 2041614972, 1573743040, 711580464, 1821519370, 156362560, -235877976, 677620420, 2000004864] total:  13
Time: 76.64697194099426      1.2774495323499044
[[2, 0, 0, 0, 3, 0, 1, 0, 4], [0, 4, 2, 3, 0, 4, 0, 0, 0], [4, 0, 0, 0, 3, 0, 1, 0, 4], [4, 5, 1, 0, 4, 0, 0, 1, 0], [0, 2, 2, 1, 0, 0, 2, 0, 3], [2, 4, 2, 3, 0, 4, 0, 0, 0], [6, 0, 0, 1, 0, 2, 0, 2, 2], [4, 1, 1, 4, 0, 0, 0, 3, 1], [1, 0, 3, 1, 0, 0, 1, 2, 3], [6, 5, 1, 0, 4, 0, 0, 1, 0], [3, 0, 1, 0, 1, 4, 1, 1, 0], [2, 2, 2, 1, 0, 0, 2, 0, 3], [8, 0, 0, 1, 0, 2, 0, 2, 2]]


In [485]:
print("iterations, ", i)

iterations,  4175629


In [486]:
print(nums)
print(results)
print(numbers)

[730049, 1017411, 1460098, 1594875, 2016603, 2034822, 2293493, 2310099, 2658659, 3189750, 3466741, 4033206, 4586986]
[[2, 0, 0, 0, 3, 0, 1, 0, 4], [0, 4, 2, 3, 0, 4, 0, 0, 0], [4, 0, 0, 0, 3, 0, 1, 0, 4], [4, 5, 1, 0, 4, 0, 0, 1, 0], [0, 2, 2, 1, 0, 0, 2, 0, 3], [2, 4, 2, 3, 0, 4, 0, 0, 0], [6, 0, 0, 1, 0, 2, 0, 2, 2], [4, 1, 1, 4, 0, 0, 0, 3, 1], [1, 0, 3, 1, 0, 0, 1, 2, 3], [6, 5, 1, 0, 4, 0, 0, 1, 0], [3, 0, 1, 0, 1, 4, 1, 1, 0], [2, 2, 2, 1, 0, 0, 2, 0, 3], [8, 0, 0, 1, 0, 2, 0, 2, 2]]
[-441954548, -1637079905, -1767818192, 1112832464, 1243146929, 2041614972, 1573743040, 711580464, 1821519370, 156362560, -235877976, 677620420, 2000004864]


In [487]:
print(primes)
print(results)
print(np.power(primes, results[0]))
print(np.power(primes, results[0]).prod()) # multiply elements of an array together

[ 2  3  5  7 11 13 17 19 23]
[[2, 0, 0, 0, 3, 0, 1, 0, 4], [0, 4, 2, 3, 0, 4, 0, 0, 0], [4, 0, 0, 0, 3, 0, 1, 0, 4], [4, 5, 1, 0, 4, 0, 0, 1, 0], [0, 2, 2, 1, 0, 0, 2, 0, 3], [2, 4, 2, 3, 0, 4, 0, 0, 0], [6, 0, 0, 1, 0, 2, 0, 2, 2], [4, 1, 1, 4, 0, 0, 0, 3, 1], [1, 0, 3, 1, 0, 0, 1, 2, 3], [6, 5, 1, 0, 4, 0, 0, 1, 0], [3, 0, 1, 0, 1, 4, 1, 1, 0], [2, 2, 2, 1, 0, 0, 2, 0, 3], [8, 0, 0, 1, 0, 2, 0, 2, 2]]
[     4      1      1      1   1331      1     17      1 279841]
-441954548


In [488]:
bignum = 5*1331*79*6889
print(bignum)

3621857305


In [489]:
import math

nparr = np.power(primes, results[0])
pythlist = nparr.tolist()
result = 1
for i in range(len(pythlist)):
    result *= pythlist[i]
print(result)


25327849228


In [490]:
## store_pows is the original matrix of powers, which we use later in the computation of y
## We don't need to concatenate the 0 row

np_array = np.array(results)
store_pows = np_array.copy()

matrixA = (np.transpose(np_array))%2
print(matrixA)
print("Number of rows, number of columns: ", len(matrixA), len(matrixA[0]))
# print(store_pows)

[[0 0 0 0 0 0 0 0 1 0 1 0 0]
 [0 0 0 1 0 0 0 1 0 1 0 0 0]
 [0 0 0 1 0 0 0 1 1 1 1 0 0]
 [0 1 0 0 1 1 1 0 1 0 0 1 1]
 [1 0 1 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 1 0 1 0 0]
 [0 0 0 1 0 0 0 1 0 1 1 0 0]
 [0 0 0 0 1 0 0 1 1 0 0 1 0]]
Number of rows, number of columns:  9 13


In [491]:
def drop_zero_rows(A): 
    return A[~np.all(A == 0, axis=1)]

In [492]:
from sympy import *

col_num = len(matrixA[0])
row_num = len(matrixA)
L = Matrix(matrixA)

aug_matrix = np.array(L.rref()[0])
aug_matrix  = drop_zero_rows(aug_matrix)

print("Reduced row echelon form is: ")
print(aug_matrix)

print("Number of rows, number of columns: ", len(aug_matrix), len(aug_matrix[0]))

Reduced row echelon form is: 
[[1 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 1 -1 0 0 0 0 1]
 [0 0 0 1 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 1 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]]
Number of rows, number of columns:  6 13


In [493]:
# v: 0s are non-free variables, 1s are fixed variables which will be 1 (free or non-free),
# 2s are fixed variables which will be 0 (free or non-free)

v = np.ones(col_num, dtype = 'int')

row_num = len(aug_matrix)   # the row_num has changed after dropping the 0 rows
# find the leading entries, aka the non-free variables, set them to 0 in the v vector
for i in range(0, row_num):
    check_main = 1
    for j in range(i, col_num):
        if(aug_matrix[i][j]==1 and check_main ==1):
            v[j]=0
            break

print(v)

[0 0 1 0 0 1 1 1 0 1 0 1 1]


In [494]:
# set one of the free variable to 1, all the rest of the free variables to 2.
## THIS IS A HUGE PLACE FOR OPTIMIZATION, IF WE PICK THE RIGHT FREE VARIABLE LIFE WILL BE EASIER LATER

delete_ones = False
for i in range(0, col_num):
    if(delete_ones==True and v[i]==1):
        v[i]=2
    if(v[i]==1):
        delete_ones = True

print(v)

[0 0 1 0 0 2 2 2 0 2 0 2 2]


In [495]:
a = np.array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1])
first = np.where(a==1)
a[a==1] = 2
a[first] = 1
print(a)

[1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1]


In [496]:
# Optimized with numpy

for i in reversed(range(0, row_num)):
    sum = np.multiply(v, aug_matrix[i]).sum()        # equal to sum = sum + sum + v[j]*aug_matrix[i][j] for all j
    sum = sum%2;
    zer =(np.argwhere(v == 0).flatten())
    if(len(zer)!=0):
        index = zer[len(zer)-1]   # last entry
        if(sum==0):
            v[index] = 2
        else:
            v[index] = 1
        
print("final v vector is ", v%2)
        

final v vector is  [1 0 1 0 0 0 0 0 0 0 0 0 0]


In [497]:
# optimized with numpy

v = v%2
print(len(v))
x = np.multiply(nums, v)     # element-wise multiplication of two arrays
print(x)
x[x==0] = 1

print(x)
int_x = 1

for k in x:
    int_x = int_x*int(k)

x = int_x      # prod is essentially multiplying elements of an array together
#print(224971*449942)

13
[ 730049       0 1460098       0       0       0       0       0       0
       0       0       0       0]
[ 730049       1 1460098       1       1       1       1       1       1
       1       1       1       1]


In [498]:

indices = flatten(np.argwhere(v==1))

new_store_pows = np.empty([len(indices), len(primes)], dtype = 'int')
i = 0
for k in indices:
    new_store_pows[i] = (np.array(store_pows[k], dtype = 'int'))
    i+=1
#print(new_store_pows)
#print(store_pows)
store_pows = new_store_pows
print(store_pows)


[[2 0 0 0 3 0 1 0 4]
 [4 0 0 0 3 0 1 0 4]]


In [499]:
y_v  = np.zeros(size_of_bound)

for i in range(len(indices)):
    y_v = np.add(y_v, store_pows[i])

y_v = y_v/2
print("y_v: ", y_v)

y = 1
z = np.power(primes, y_v)
print(z)
y = y*z


y = np.prod(y)   # no need to check y_v == 0, since anything raised to 0 is 1, and on multiplication, 1 has no effect
    
print("x is ", x, ", y is ", y)
print(101223901682 - 110880000)

y_v:  [3. 0. 0. 0. 3. 0. 1. 0. 4.]
[8.00000e+00 1.00000e+00 1.00000e+00 1.00000e+00 1.33100e+03 1.00000e+00
 1.70000e+01 1.00000e+00 2.79841e+05]
x is  1065943084802 , y is  50655698456.0
101113021682


In [500]:
def gcd(a, b):
    a,b = b, a%b
    print(a, b)
    return a

In [501]:
if(the_number%int(x -int(y)) == 0):
    k = int(x -int(y))
else:
    k = gcd(int(x -int(y))%the_number, the_number)

end_time = time.time()
print('Factor 1: ',k)
print ('Factor 2: ', int(the_number/k)) 
print('Runtime in seconds: ', round(calc_time(begin_time, end_time), 4))

169214564391 0
Factor 1:  169214564391
Factor 2:  1
Time: 76.95597434043884      1.2825995723406474
Runtime in seconds:  76.956
